# Diagnóstico CPP · 07 de Maio · 2026
# 6 cirurgiões agendados em diagnóstico individual de 1h com Patrick Suyti + Dr. Mateus Jerônimo

# ============================================================================
# IG_ANALISE — Análise profunda do Instagram (uso interno painel operacional)
# ============================================================================
IG_ANALISE = {
    "marianna-monteiro": {
        "foto": "https://unavatar.io/instagram/dra.marimonteirov",
        "handle": "@dra.marimonteirov ✓ (verificado azul)",
        "url": "https://www.instagram.com/dra.marimonteirov/",
        "verificado": True,  # selo azul confirmado via print 07/05/2026
        "seguidores": "10.200",
        "posts": "397",
        "seguindo": "2.093",
        "bio_literal": '"dra.marimonteirov ✓ · Dra. Marianna Monteiro | Bariátrica" — bio expandida: "Médica · Brasília • Cirurgiã • Bariátrica · Te ajudo com a obesidade através do tratamento cirúrgico · CRM: 24276 • RQE: 18912" · linktr.ee/dra.marimonteirov · 82,1 mil alcançadas (insights)',
        "tom": "Foto profissional P&B premium · postura de autoridade (terno preto · braços cruzados) · bio com promessa comercial DIRETA ('Te ajudo com a obesidade através do tratamento cirúrgico') · sistema de funil estruturado em destaques",
        "conteudo": [
            "**7 destaques estruturados em funil**: CORAGEM! · Oiii · DESAFIO · Bari Clube · Comece aqui · Cirurgias Bari · #BARIGAN",
            "**'Bari Clube'** = programa/comunidade própria nomeada (sinal forte de método empacotado)",
            "**'#BARIGAN'** = movimento/categoria criada por ela (capital simbólico próprio)",
            "**'DESAFIO' + 'CORAGEM!'** = trabalha narrativas de transformação emocional, não só técnica",
            "**'Comece aqui'** = funil de entrada explícito",
            "82.100 alcançadas (insights públicos) = alcance MAIOR que audiência = está performando no algoritmo",
            "397 posts em ~3 anos = produção consistente · ratio 25 seg/post (saudável)",
            "Linktree comercial ativo",
        ],
        "branding": "ALTO · foto P&B autoridade · bio com promessa de marketing direto · método empacotado nomeado (Bari Clube) · movimento próprio (#BARIGAN) · 7 highlights organizados em funil. Identidade premium consolidada · não é mais 'aluna do Renato'.",
        "diagnostico": "Print MUDA O DIAGNÓSTICO. Marianna NÃO é Gavião com identidade dual — ela é ÁGUIA em ascensão. Já tem Bari Clube (programa próprio), #BARIGAN (movimento), foto premium P&B, selo azul verificado, 82k alcançadas, 7 highlights em funil. O ativo digital está MONTADO. O que falta agora não é construir marca — é capitalizar o ativo em ticket premium e em escala nacional. Cobrar pela transformação que o Bari Clube já entrega · escalar #BARIGAN como categoria nacional.",
        "gaps_ig": [
            "Bio cita CRM/RQE mas não cita HRAN/Renato Teixeira/Galvão = autoridade técnica gigante não comunicada",
            "10.200 seguidores apesar de 82k alcançadas = está dependente de viralizar (não conversão→audiência)",
            "Bari Clube é programa nomeado mas não tem ticket público transparente · vende como CTA fechado",
            "Atende Brasília + Planaltina-GO em paralelo = ainda divide foco premium",
        ],
        "score_visual": 78,  # subiu de 48 — print revelou ativo muito mais avançado
    },
    "pitagoras-kieling": {
        "foto": "https://unavatar.io/instagram/pitagoraskieling",
        "handle": "@pitagoraskieling",
        "url": "https://www.instagram.com/pitagoraskieling/",
        "verificado": False,
        "seguidores": "—",
        "posts": "—",
        "seguindo": "—",
        "bio_literal": "[Instagram bloqueia leitura · perfil profissional ativo · provável <5k seguidores baseado em padrão de presença digital geral]",
        "tom": "Geração analógica · email Hotmail · sites Wix simples · presença básica · médico técnico de elite com produção digital embrionária",
        "conteudo": [
            "Perfil profissional ativo na clínica de São Leopoldo · Hospital Centenário",
            "Site oficial drpitagoraskieling.com.br + página Wix complementar pkielingjr.wixsite.com",
            "Facebook ativo facebook.com/drpitagoraskieling",
            "Google Business profile: dr-pitagoras-kieling-junior.business.site",
            "Sem identidade visual forte, sem produção de conteúdo regular, sem persona médica construída",
        ],
        "branding": "Básico · vitrines simples · sem persona digital · enorme upside de marketing",
        "diagnostico": "Pitágoras é pato técnico de elite escondido em Vale dos Sinos. UFSM Medicina 1994 + Residência Cirurgia Geral + Coloproctologia Hospital Ernesto Dorneles + IRCAD Strasbourg 2014-15 + Padronização Lübeck 2017 + 10.000+ colonoscopias + 928 avaliações 5⭐ Doctoralia. Mas: ticket R$480 consulta + Unimed/IPÊ dominando volume + capital social R$88k (sócio único) + ativos digitais simples. 25 anos de carreira como funcionário do próprio talento.",
        "gaps_ig": [
            "Cobrança subprecificada: R$480 consulta sendo IRCAD+Lübeck = metade do que vale",
            "Sem identidade visual digital · sites são Wix simples, não premium",
            "10.000+ colonoscopias e 928 reviews 5⭐ = ativo gigante não capturado em audiência",
            "Sem livro, curso, mentoria — capacidade científica precoce (paper genética 1991) que parou de publicar",
        ],
        "score_visual": 35,
    },
    "paulo-victor-pereira": {
        "foto": "https://unavatar.io/instagram/clinicaicod",
        "handle": "@clinicaicod (institucional · sem perfil pessoal)",
        "url": "https://www.instagram.com/clinicaicod/",
        "verificado": False,
        "seguidores": "1.870",
        "posts": "114",
        "seguindo": "333",
        "bio_literal": "[sem perfil pessoal · marca diluída em @clinicaicod junto com 9 outros sócios]",
        "tom": "Inexistente como marca pessoal · presença 100% institucional dentro da ICOD",
        "conteudo": [
            "Posts da clínica · não pessoais",
            "Sem rosto-protagonista do Paulo Victor",
            "Sem nicho declarado, sem ângulo único",
            "Frequência baixa do perfil institucional",
        ],
        "branding": "Inexistente como marca pessoal · 7 anos de carreira sem identidade digital própria · paciente premium que pesquisa 'Dr. Paulo Victor' em Brasília não encontra · encontra a ICOD",
        "diagnostico": "Paulo Victor é o caso mais limpo do dia: reputação técnica é cravada (151 reviews 5⭐ no Doctoralia) mas a autoridade individual está dentro de uma sociedade de 10. A engrenagem cobra ticket de funcionalismo público porque é assim que paciente Postal/Camed acha a clínica. **Nota: 2ª call CPP em 2 dias — diagnóstico aprofundado.**",
        "gaps_ig": [
            "Sem Instagram pessoal em 2026",
            "Sem nicho declarado dentro de pé/tornozelo",
            "Sem rosto-protagonista público",
            "Sem ponto de captura individual fora do Doctoralia",
        ],
        "score_visual": 18,
    },
    "ildo-golff": {
        "foto": "https://unavatar.io/instagram/drildogolff",
        "handle": "@drildogolff (a confirmar)",
        "url": "https://www.instagram.com/drildogolff/",
        "verificado": False,
        "seguidores": "—",
        "posts": "—",
        "seguindo": "—",
        "bio_literal": "[handle não-óbvio ou perfil privado · não indexa publicamente]",
        "tom": "Inexistente publicamente · cirurgião novo (38 anos · saiu da residência em 2024) · cabeça contábil + médica · zero estratégia digital construída",
        "conteudo": [
            "Sem footprint indexado · provavelmente conta privada ou recém-aberta",
            "Não há posts visíveis em buscas",
            "Ausência total = território digital VIRGEM",
        ],
        "branding": "Zero · perfil ainda não construído",
        "diagnostico": "Ildo é o cirurgião que sabe ler DRE — bacharel em Ciências Contábeis pela Univel ANTES de fazer Medicina pela FAG. Pai economista/perito judicial TRT9 com 146 processos como perito. Compartilha o mesmo prédio com o pai. Família de tradição contábil em Cascavel. Acabou de virar neurocirurgião pós-PUC-Cajuru (2024). Ainda em pronto-atendimento Santa Helena/PR como complemento de renda. CRM-PR 40772.",
        "gaps_ig": [
            "Sem Instagram profissional indexado · território digital VIRGEM",
            "Sem Doctoralia, BoaConsulta, sem reviews",
            "Capital social da clínica R$ 5 mil · subdimensionado pra um neurocirurgião",
            "Pronto-atendimento Santa Helena 20h/sem = sintoma de transição residente → empresário particular",
        ],
        "score_visual": 12,
    },
    "vitor-vilhegas": {
        "foto": "https://unavatar.io/instagram/drvitorvilhegas",
        "handle": "@drvitorvilhegas",
        "url": "https://www.instagram.com/drvitorvilhegas/",
        "verificado": False,
        "seguidores": "—",
        "posts": "—",
        "seguindo": "—",
        "bio_literal": '"Dr. Vítor Vilhegas · Ortopedista · Cirurgia do Joelho · Adamantina-SP" · drvitorvilhegas.com.br · Reel recente: "Estamos de casa nova!" (mudança de consultório recente)',
        "tom": "Médico premium em construção · investiu em equipamento (navegação intra-operatória) e em marketing (site + IG + FB) · perfil profissional, posts cirurgia/equipe/tecnologia · faz por intuição, ainda sem sistema",
        "conteudo": [
            "Posts sobre cirurgia, equipe e tecnologia",
            "Reel recente: mudança de consultório (Av. Rio Branco 61, Centro Adamantina)",
            "Linha editorial técnica · centrada em joelho premium",
            "Site próprio, IG, Facebook, presença ampla em portais médicos",
        ],
        "branding": "Médio-alto em produção · investiu deliberadamente · MAS sem sistema · faz por intuição · enorme upside de método",
        "diagnostico": "Vitor é o cirurgião que JÁ entendeu que precisa de marketing. Em julho/2025 foi DESTAQUE NO SIGA MAIS de Adamantina como **PIONEIRO REGIONAL em prótese unicompartimental de joelho com NAVEGAÇÃO INTRA-OPERATÓRIA** (trouxe Dr. Álvaro Souto de Dourados/MS como cirurgião convidado). Ortocity-SP no currículo (joelho premium). Família de dentistas em Pres. Prudente (pai/tio Sérgio Vilhegas, dentista UNOESTE) — escolheu Adamantina pra construir nome próprio. Adamantina é praticamente monopólio do joelho.",
        "gaps_ig": [
            "Pioneirismo da navegação rendeu UMA matéria local em 2025 e morreu — material gigante de marketing não capitalizado",
            "Adamantina (35k hab) sustenta consultório, mas só com captação regional ampla (Lucélia, Osvaldo Cruz, Dracena, Pres. Prudente)",
            "Sem método estruturado de marketing — investiu em peças, falta funil",
            "Sem narrativa de marca pessoal além da técnica",
        ],
        "score_visual": 58,
    },
    "alander-sobreira": {
        "foto": "https://unavatar.io/instagram/dralandersobreira",
        "handle": "@dralandersobreira",
        "url": "https://www.instagram.com/dralandersobreira/",
        "verificado": False,
        "seguidores": "28.000",
        "posts": "435",
        "seguindo": "—",
        "bio_literal": '"Neurocirurgião especializado em crânio e coluna vertebral. CRM-CE 10374, RQE 6258. Contato 981400077."',
        "tom": "Médico-pastor · não é influencer-de-Maybach · humanizado, didático, NÃO performático · linguagem cristã evangélica · gratidão > militância",
        "conteudo": [
            "Mix em 3 pilares: 50% educação técnica (tumor cerebral, hérnia disco, Parkinson, AVC, escoliose) · 25% fé/reflexão cristã · 25% saúde pública/advocacy",
            "Hashtags técnicas: #tumorescerebrais #neurocirurgiao #neuro",
            "Posts de gratidão de fim de ano: 'tudo começa e termina em Deus, a graça é que sustenta quando a técnica alcança seu limite' (24/12/2025)",
            "Threads: 3.208 seguidores · canal subaproveitado",
            "Frequência baixa-média (~2-4 posts/mês em 2025)",
        ],
        "branding": "Sólido autêntico · médico-servo · 28k em IG com 435 posts = 64 seg/post (engajamento real, não inflado) · identidade cristã pública é âncora identitária central",
        "diagnostico": "Alander é Águia AAA real — Rush Chicago + 13 anos OTO Kora Aldeota + 28k IG + cristão público + palestrante NeuroCeará 2025 + coordenador neuro OTO desde 2014. Mas: Doctoralia VAZIA (zero reviews públicas), zero PubMed, zero produto/livro/curso. **3 alavancas mortas + 2 eixos de aliança**: fé compartilhada com Patrick + trajetória interior→cima (FMJ Juazeiro→Behrens BH→Rush Chicago→Fortaleza+Sobral).",
        "gaps_ig": [
            "Doctoralia 'Avaliações em breve' apesar de 13 anos · capital social do paciente não capturado",
            "Zero papers PubMed · cabeça técnica não converteu em produção científica",
            "Frequência IG baixa (2-4/mês) pra perfil de 28k seguidores",
            "Sem livro, curso, produto digital · autoridade vazando · Rush + 28k = barril de pólvora não acendido",
        ],
        "score_visual": 75,
    },
}


# ============================================================================
# OFERTA · 12 elementos do programa Cirurgião Particular Premium
# ============================================================================
OFERTA = [
    {"cat": "MENTORIA", "icon": "🎯", "nome": "3 Mentorias individuais PREMIUM", "valor": "R$ 100.000", "imensuravel": False, "highlight": True},
    {"cat": "MENTORIA", "icon": "👥", "nome": "Mentorias semanais em grupo com Patrick e/ou Mateus", "valor": "R$ 60.000", "imensuravel": False},
    {"cat": "MENTORIA", "icon": "🚀", "nome": "Onboarding PREMIUM com Patrick e/ou Mateus", "valor": "R$ 30.000", "imensuravel": False},
    {"cat": "MÉTODO", "icon": "📚", "nome": "Área de membros com método PREMIUM (7 pilares)", "valor": "R$ 20.000", "imensuravel": False},
    {"cat": "MÉTODO", "icon": "🗺️", "nome": "Plano de ação acompanhado", "valor": "R$ 30.000", "imensuravel": False},
    {"cat": "PRESENCIAL", "icon": "🏛️", "nome": "2 Imersões presenciais/ano (6-7/Ago SP + Mar/27)", "valor": "R$ 10.000", "imensuravel": False},
    {"cat": "PRESENCIAL", "icon": "🩺", "nome": "2 Oficinas para a sua equipe médica", "valor": "R$ 40.000", "imensuravel": False},
    {"cat": "SUPORTE", "icon": "💬", "nome": "Suporte PREMIUM individual via WhatsApp", "valor": "R$ 10.000", "imensuravel": False},
    {"cat": "COMUNIDADE", "icon": "🤝", "nome": "Grupo com outros cirurgiões mentorados", "valor": "Imensurável", "imensuravel": True},
    {"cat": "COMUNIDADE", "icon": "🔑", "nome": "Grupo direto com Patrick e Mateus", "valor": "Imensurável", "imensuravel": True},
    {"cat": "RITUAL", "icon": "💎", "nome": "Ritual de primeira cirurgia particular R$50k+", "valor": "Imensurável", "imensuravel": True},
    {"cat": "ELITE", "icon": "👑", "nome": "Club PREMIUM 100K", "valor": "Imensurável", "imensuravel": True},
]
OFERTA_VALOR_TOTAL_MENSURAVEL = 300000
OFERTA_TOTAL_ELEMENTOS = len(OFERTA)
OFERTA_INTANGIVEIS = sum(1 for o in OFERTA if o["imensuravel"])

PRECO_PADRAO = 60000
PRECO_DESCONTO_PCT = 20
PRECO_EXCLUSIVO = int(PRECO_PADRAO * (1 - PRECO_DESCONTO_PCT/100))   # R$ 48.000


# ============================================================================
# CIRURGIOES — 6 agendados em 07/05/2026
# ============================================================================
CIRURGIOES = [
    # ===== 1 · 10h · Marianna Monteiro Vaz da Silva =====
    {
        "slug": "marianna-monteiro",
        "ordem": 1,
        "hora": "10:00",
        "zoom": "https://us06web.zoom.us/j/85290759945",
        "nome": "Dra. Marianna Monteiro Vaz da Silva",
        "nome_lista": "Dra Marianna Monteiro",
        "correcao_grafia": None,
        "especialidade": "Cirurgia Geral",
        "subespecialidade": "Cirurgia Bariátrica e Metabólica",
        "cidade": "Brasília",
        "estado": "DF",
        "crm": "CRM-DF 24276 · RQE 18912",
        "formacao": [
            "Residência em Cirurgia Geral · Hospital Regional da Asa Norte (HRAN/SES-DF)",
            "Fellowship/aperfeiçoamento em Cirurgia Bariátrica · HRAN/SES-DF — sob Dr. Renato Alves Teixeira Lima e Dr. Rafael Oliveira Galvão",
            "RQE 18912 — qualificação obtida nos últimos ~5 anos",
            "Co-autora de poster científico SBCBM 2022 — primeira autora do caso 'Fístula Gastrogástrica Pós Gastroplastia em Y de Roux' (PE-80)",
        ],
        "estruturas": [
            "Atende em Brasília (capital) — provável Hospital Santa Lúcia · Asa Sul",
            "Atendimento secundário em Planaltina-GO (entorno do DF)",
            "Equipe multidisciplinar bariátrica (psicólogo · nutricionista · endocrino) · padrão SBCBM",
        ],
        "credenciais": [
            "Linhagem HRAN/SES-DF: Dr. Renato Alves Teixeira Lima (fundador serviço metabólica DF, +16 mil cirurgias) e Dr. Rafael Oliveira Galvão (coordenador SES-DF desde 2008, +10 mil procedimentos)",
            "Apresentação como primeira autora · 24º Congresso Brasileiro de Cirurgia Bariátrica e Metabólica (SBCBM 2022)",
            "Bariátrica em Brasília — uma das praças com maior poder aquisitivo do Brasil",
        ],
        "instagram": "@dra.marimonteirov ✓ (verificado azul)",
        "instagram_url": "https://www.instagram.com/dra.marimonteirov/",
        "instagram_aberto": True,
        "instagram_seguidores": "10.200",
        "instagram_posts": "397",
        "instagram_bio": '"Dra. Marianna Monteiro | Bariátrica · Médica · Brasília • Cirurgiã • Bariátrica · Te ajudo com a obesidade através do tratamento cirúrgico · CRM: 24276 • RQE: 18912 · linktr.ee/dra.marimonteirov · 82,1 mil alcançadas"',
        "instagram_tom": "Selo azul · foto P&B premium · bio com promessa de marketing direto · 7 highlights em funil (CORAGEM! · Oiii · DESAFIO · Bari Clube · Comece aqui · Cirurgias Bari · #BARIGAN) · 82,1k alcançadas mensais",
        "site": None,
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": '"Te ajudo com a obesidade através do tratamento cirúrgico"',
        "posicionamento_atual_publico": "Cirurgiã bariátrica de Brasília · linhagem HRAN/SES-DF (Renato Teixeira + Galvão) · primeira autora SBCBM 2022. Tem perfil verificado azul, 10.200 seguidores e 82.100 alcançadas mensais, programa próprio nomeado (Bari Clube), movimento próprio (#BARIGAN), e funil de entrada estruturado em destaques (CORAGEM! · DESAFIO · Comece aqui).",
        "potencial_publico": "Marianna, você fez algo que poucos cirurgiões bariátricos do Brasil fizeram: <strong>criou movimento próprio (#BARIGAN) e programa empacotado (Bari Clube).</strong> Tem selo azul, 10.200 seguidores, 82 mil alcançadas, 7 highlights em funil. <em>O ativo digital está MONTADO.</em> O que falta não é construir — é capitalizar. Transformar o Bari Clube em ticket premium definido. Escalar #BARIGAN como categoria nacional. Permissão pra cobrar pela transformação que o seu sistema já entrega.",
        "perfil_cpp": "ÁGUIA EM ASCENSÃO (corrigido pós-print · não é mais Gavião)",
        "score_compra": 84,
        "perfil_evidencias": [
            "**Selo azul VERIFICADO** + 10.200 seguidores + 82.100 alcançadas mensais = ativo digital MONTADO",
            "**Bari Clube** = programa/comunidade própria nomeada (método empacotado)",
            "**#BARIGAN** = movimento/categoria criada por ela (capital simbólico próprio)",
            "**7 highlights em funil estruturado** (CORAGEM! · Oiii · DESAFIO · Bari Clube · Comece aqui · Cirurgias Bari · #BARIGAN)",
            "Foto profissional P&B autoridade · bio com promessa de marketing direto",
            "Linhagem HRAN/SES-DF + primeira autora SBCBM 2022 = autoridade técnica + movimento digital próprio",
            "Pagou sinal R$1k = busca por próxima fronteira (não construção inicial)",
        ],
        "dores_top3": [
            ("Capital subaproveitado · cobrança incoerente com o ativo", "Programa próprio (Bari Clube) + movimento (#BARIGAN) + selo azul + 82k alcançadas = você JÁ entrega transformação. Mas o ticket atual provavelmente está abaixo do que entrega. Permissão pra cobrar pelo PROGRAMA, não pela cirurgia, ainda não foi internalizada."),
            ("Linhagem HRAN não comunicada na bio", "Bio cita CRM/RQE mas não cita Renato Teixeira/Galvão · não cita primeira autoria SBCBM 2022. Autoridade técnica gigante não está sendo amplificada como deveria."),
            ("Atende Brasília + Planaltina-GO simultaneamente", "Operação dual = ainda divide foco entre Premium (capital) e volume (entorno). Quer migrar 100% pra Premium puro mas tem medo de soltar a praça antiga."),
        ],
        "gaps": [
            ("Bari Clube sem ticket público transparente", "Programa nomeado existe, mas vende como CTA fechado. Falta posicionar como produto premium definitivo · ticket único · transformação completa · jornada empacotada."),
            ("#BARIGAN como categoria nacional", "Movimento existe em Brasília mas não escalou nacional. Sem produto digital, sem mentoria pra outros bariátricos, sem livro/curso. Categoria poderia ser nacional em 12-18 meses."),
            ("Mídia tier-1 não furada", "Brasília tem Correio, Metrópoles, R7, podcasts nacionais. Selo azul + Bari Clube + #BARIGAN é narrativa pronta · falta amplificação."),
        ],
        "hooks_abertura": [
            "Marianna, você fez algo que poucos bariátricos do Brasil fizeram: criou movimento próprio (#BARIGAN) e programa empacotado (Bari Clube). Selo azul, 82k alcançadas, 7 highlights em funil. Cadê o ticket coerente com tudo isso?",
            "Bari Clube é nome de programa, não nome de consulta. Você tem método empacotado e cobra como cirurgia avulsa. Por que?",
            "Sua bio diz 'Te ajudo com a obesidade através do tratamento cirúrgico'. Promessa direta. Mas não cita HRAN, Renato Teixeira, Galvão, primeira autoria SBCBM 2022. Autoridade técnica gigante invisível.",
            "82 mil alcançadas e 10 mil seguidores = você está performando no algoritmo MAIS do que sua audiência captura. Conversão alcance → seguidor → paciente premium é o gargalo · não falta de produção.",
            "Atender Brasília e Planaltina-GO ao mesmo tempo · qual percentual do seu faturamento é cada um hoje? Quanto seria se você concentrasse 100% em Brasília Premium?",
        ],
        "objecoes_esperadas": [
            "'Tenho fluxo via convênio + indicação multidisciplinar — não posso largar o que tá funcionando'",
            "'Brasília tem muita concorrência bariátrica — Renato, Galvão, vários nomes consolidados'",
            "'Bariátrica tem ticket apertado pra plano de saúde'",
            "'Eu não quero virar influencer'",
        ],
        "abordagem_recomendada": "Tom peer-to-peer · Águia em ascensão (NÃO tratar como Gavião nem fingir que está construindo). Patrick: validar Bari Clube + #BARIGAN + selo azul + 82k alcançadas = autoridade já existente · provocar 'cobre pelo programa, não pela cirurgia'. Mateus: trazer caso de bariátrica Águia CPP que transformou método nomeado em ticket premium nacional. CPP não é pra construir marca — é pra capitalizar o ativo que ela JÁ tem em ticket coerente e em escala nacional.",
        "alerta_homonimo": "100% confiança. Co-autora SBCBM 2022 batida com Renato Teixeira + Galvão + Elias José Guedes Lima. Score 78 GAVIÃO confirmado.",
        "fontes": [
            "https://www.congressobariatrica.com.br/2022/programacao/tl.php?id_atividade=695",
            "https://drrenatoteixeira.com.br/",
            "https://www.instagram.com/dra.marimonteirov/",
            "https://linktr.ee/dra.marimonteirov",
        ],
        "pre_diagnostico": {
            "frase_central": "Você criou movimento próprio (#BARIGAN) e programa empacotado (Bari Clube). O ativo digital está montado. Falta capitalizar em ticket coerente e em escala nacional.",
            "pontos": [
                "Selo azul verificado · 10.200 seguidores · 82.100 alcançadas mensais · 397 posts · 7 highlights em funil = ativo digital de Águia.",
                "Bari Clube é programa próprio nomeado · #BARIGAN é movimento próprio · 'CORAGEM!' + 'DESAFIO' + 'Comece aqui' = funil estruturado de entrada e transformação emocional.",
                "Linhagem HRAN/SES-DF (Renato Teixeira + Galvão) + primeira autora SBCBM 2022 = autoridade técnica que ninguém questiona — MAS não está comunicada na bio.",
                "Você está alcançando 82 mil pessoas/mês mas convertendo apenas em 10 mil seguidores · e ticket atual provavelmente está abaixo do que entrega via Bari Clube.",
            ],
            "no_central": "Você não precisa construir marca · você JÁ tem. Precisa de PERMISSÃO pra cobrar pelo programa (não pela cirurgia) e de ESCALA pra transformar #BARIGAN em categoria nacional. CPP não te ensina nada novo — te ajuda a sistematizar e escalar o ativo que você já criou.",
        },
        "plano_acao": [
            {
                "fase": "30 dias",
                "titulo": "Capitalizar Bari Clube como produto premium",
                "acoes": [
                    "Definir ticket público do Bari Clube · jornada completa (pré + cirurgia + acompanhamento 12-24m + comunidade) · R$ 45-75k ticket único",
                    "Adicionar HRAN + Renato Teixeira/Galvão + primeira autoria SBCBM 2022 explícitos na bio (autoridade técnica não comunicada)",
                    "Subir consulta avaliativa pra R$ 800-1.500 (filtro de qualificação · paciente premium Brasília)",
                    "Capturar depoimentos em vídeo das próximas 10 pacientes do Bari Clube — banco de prova social premium em vídeo",
                ],
            },
            {
                "fase": "60 dias",
                "titulo": "Concentrar em Brasília Premium",
                "acoes": [
                    "Plano de saída gradual de Planaltina-GO · concentrar 100% em Brasília Asa Sul/Lago Sul/Águas Claras",
                    "Site próprio dramariannamonteiro.com.br + página Bari Clube + página #BARIGAN com depoimentos e jornada",
                    "Cadastrar Doctoralia + BoaConsulta · capturar reviews acumuladas",
                    "ICP servidor público federal alto-padrão (Senado · Câmara · STF · Itamaraty) + empresário Águas Claras/Lago Sul",
                ],
            },
            {
                "fase": "90 dias",
                "titulo": "Escalar #BARIGAN como categoria nacional",
                "acoes": [
                    "Mídia tier-1 DF: Correio Braziliense, Metrópoles, R7, podcasts (Saúde em DF, ICL Notícias)",
                    "Lançar produto digital · curso ou livro sobre o método Bari Clube (escala fora da agenda cirúrgica)",
                    "Mentoria pra outros bariátricos que querem replicar o sistema · monetizar #BARIGAN como categoria",
                    "Aparições mídia nacional (BAND, GloboNews, Você Saúde) em torno de jornada bariátrica + saúde da mulher",
                ],
            },
        ],
    },

    # ===== 2 · 11h · Pitágoras Kieling Júnior =====
    {
        "slug": "pitagoras-kieling",
        "ordem": 2,
        "hora": "11:00",
        "zoom": "https://us06web.zoom.us/j/81790213253",
        "nome": "Dr. Pitágoras Kieling Júnior",
        "nome_lista": "Dr Pitágoras Júnior",
        "correcao_grafia": None,
        "especialidade": "Coloproctologia",
        "subespecialidade": "Cirurgia Geral · Colonoscopia · Videolaparoscopia colorretal avançada",
        "cidade": "São Leopoldo",
        "estado": "RS",
        "crm": "CRM-RS 20637",
        "formacao": [
            "Graduação Medicina · UFSM Universidade Federal de Santa Maria (1989-1994)",
            "Residência Cirurgia Geral · Hospital Ernesto Dorneles · Porto Alegre (1995-1997, bolsista MEC)",
            "Residência Coloproctologia · Hospital Ernesto Dorneles (1998-1999)",
            "Treinamento avançado IRCAD · Strasbourg/Latam (2014-2015) · videolaparoscopia",
            "Padronização técnica videolaparoscópica colorretal · Instituto Lübeck São Paulo (2017)",
        ],
        "estruturas": [
            "Clínica Endosinos · Rua Ivo Afonso 62 · Bairro Fião · São Leopoldo (CNPJ 07.370.887/0001-59 · Diretor Técnico desde 2005)",
            "Hospital Centenário · São Leopoldo",
            "Hospital Regina · Novo Hamburgo (staff coloproctologia desde 2009)",
            "Unimed Vale dos Sinos (coloproctologista/colonoscopista desde 2013)",
            "Hospital Getúlio Vargas · Sapucaia do Sul (Diretor Técnico Endoscopia Digestiva)",
            "+16.000 procedimentos acumulados na Endosinos",
        ],
        "credenciais": [
            "+10.000 colonoscopias realizadas (volume top-tier)",
            "Trilíngue: Português · Espanhol · Inglês",
            "928 avaliações verificadas Doctoralia · 5 estrelas",
            "Co-autor 'Sugestão Preliminar do Efeito Trivers-Willard em Seres Humanos' (Brazilian Journal of Genetics, 1991 · ainda na graduação)",
            "Co-autor 'Adenoma Mucinoso de Apêndice' (58º Congresso Brasileiro de Coloproctologia, 2009)",
            "25 anos de carreira · CRM-RS 20637",
        ],
        "instagram": "@pitagoraskieling",
        "instagram_url": "https://www.instagram.com/pitagoraskieling/",
        "instagram_aberto": True,
        "instagram_seguidores": "—",
        "instagram_posts": "—",
        "instagram_bio": "[Instagram bloqueia leitura · perfil profissional ativo]",
        "instagram_tom": "Geração analógica · email Hotmail · sites Wix simples · presença básica · médico técnico de elite com produção digital embrionária",
        "site": "https://www.drpitagoraskieling.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/pitagoras-kieling-junior/coloproctologista/sao-leopoldo",
        "linkedin": None,
        "tagline_atual": '"Coloproctologista · Cirurgia Geral · Colonoscopia"',
        "posicionamento_atual_publico": "Coloproctologista de Vale dos Sinos com 25 anos de carreira, IRCAD Strasbourg + Lübeck no currículo, +10.000 colonoscopias, 928 avaliações 5 estrelas no Doctoralia. Atende em 5 frentes hospitalares simultaneamente.",
        "potencial_publico": "Pitágoras, +10 mil colonoscopias é número de cirurgião que parou de contar — e você cobra R$ 480 a consulta. IRCAD Strasbourg e Lübeck no seu currículo é Ferrari rodando em estrada de chão. <strong>O que você precisa não é começar.</strong> É reconhecer que sua técnica é de centro de excelência mundial — e construir a estrutura que cobre coerente.",
        "perfil_cpp": "PATO em transição pra URUBU (técnico de elite escondido)",
        "score_compra": None,
        "perfil_evidencias": [
            "+10.000 colonoscopias + 928 reviews 5⭐ Doctoralia = ativo gigante",
            "IRCAD Strasbourg + Lübeck = formação de elite mundial",
            "Sócio único capital R$88k = empresa enxuta, ainda não estruturada como negócio",
            "Atende 5 hospitais + Unimed/IPÊ = volume convênio dominando",
            "Inscreveu-se no Desafio CPP aos 55 anos = decisão de mudar de patamar",
        ],
        "dores_top3": [
            ("Currículo Champions, ticket Série C", "R$ 480 consulta sendo IRCAD + Lübeck = 50% abaixo do que coloproctologistas com metade do CV cobram em SP/POA. Subprecificação clássica."),
            ("Operador solo sobrecarregado", "5 frentes hospitalares simultâneas (Centenário, Regina NH, Unimed Vale, Sapucaia) + clínica enxuta capital R$88k = troca tempo por dinheiro, não constrói ativo escalável."),
            ("Cabeça científica que parou no meio", "Paper de genética em 1991 (ainda na graduação) + caso colonoscópico em 2009 = 30+ anos sem produção contínua. Capacidade que não virou linha de pesquisa, livro ou autoridade pública."),
        ],
        "gaps": [
            ("Sem identidade visual digital", "Site Wix simples + Facebook + Google Business básico = vitrines, não plataforma. Geração que ainda não internalizou que digital é ativo."),
            ("Sem produto premium estruturado", "Vende consulta avulsa + colonoscopia avulsa + cirurgia. Falta jornada de prevenção colorretal premium · pacote screening + acompanhamento + cirurgia eletiva."),
            ("Marca pessoal apagada", "928 reviews 5⭐ depositadas em Doctoralia · não convertidas em autoridade-marca pública. Tom 'paciente' (paciência, calma, não tem pressa) é ouro de copy nunca usado."),
        ],
        "hooks_abertura": [
            "Pitágoras, +10 mil colonoscopias é número de cirurgião que parou de contar — e você cobra R$ 480 a consulta. A gente precisa conversar sobre o quanto você vale.",
            "IRCAD Strasbourg e Lübeck no currículo de coloproctologista que atende IPÊ é Ferrari rodando em estrada de chão. Vamos botar pista.",
            "São Leopoldo te formou um nome, mas sua técnica é de centro de excelência mundial. Por que o Vale dos Sinos é seu teto e não seu trampolim?",
            "Você publicou Trivers-Willard em 1991, antes de formar. Cabeça científica não morre — ela só espera outro fôlego. Esse fôlego é o que a gente vai destravar.",
            "Você é Diretor Técnico em 3 hospitais e sócio único de uma clínica de R$ 88 mil de capital. Você é o ativo, e não tem ativo. Isso muda agora.",
            "928 pacientes te dão 5 estrelas e dizem que você não tem pressa. Você construiu autoridade — falta arquitetura pra que ela vire patrimônio.",
        ],
        "objecoes_esperadas": [
            "'Tenho fluxo grande via Unimed Vale dos Sinos · não posso descredenciar'",
            "'Em São Leopoldo não cabe ticket de capital'",
            "'Eu não sou de aparecer · prefiro o trabalho clínico'",
            "'Estou na fase final da carreira — pra quê CPP agora?'",
        ],
        "abordagem_recomendada": "Tom respeitoso (sênior 55 anos · 25 anos de carreira). Patrick valida volume + IRCAD + Lübeck = currículo Champions League. Provocação ouro: 'Júnior virou referência. E o Pitágoras Sênior, pai, viu até onde?' (gancho emocional pelo nome). CPP é sobre arquitetar o LEGADO técnico em ativo escalável + monetização coerente — sem virar influencer.",
        "alerta_homonimo": "100% confiança. CRM-RS 20637 confirmado em CREMERS + Doctoralia + Endosinos + Escavador. UFSM 1994 + Hospital Ernesto Dorneles + IRCAD/Lübeck = match único.",
        "fontes": [
            "https://www.doctoralia.com.br/pitagoras-kieling-junior/coloproctologista/sao-leopoldo",
            "https://www.drpitagoraskieling.com.br/",
            "https://www.clinicaendosinos.com/",
            "https://www.escavador.com/sobre/2895934/pitagoras-kieling-junior",
            "https://www.facebook.com/drpitagoraskieling/",
            "https://www.instagram.com/pitagoraskieling/",
        ],
        "pre_diagnostico": {
            "frase_central": "Currículo Champions League cobrando preço de Série C. 25 anos de excelência técnica que ainda não viraram um patrimônio.",
            "pontos": [
                "UFSM Medicina 1994 + Residência Cirurgia + Coloproctologia Ernesto Dorneles + IRCAD Strasbourg + Lübeck = formação que cabe em qualquer centro do mundo.",
                "+10.000 colonoscopias + 928 avaliações 5 estrelas = volume e prova social que poucos têm no Brasil.",
                "Mas: 5 frentes hospitalares simultâneas + clínica capital R$ 88k + ticket R$ 480 + Unimed/IPÊ dominando volume = você é o ativo, mas não construiu ativo.",
                "Paper de genética em 1991 (ainda graduação) + 2009 = capacidade científica que parou no meio. 30+ anos depois, ainda não tem livro, curso, mentoria, podcast.",
            ],
            "no_central": "Você não precisa de mais técnica nem de mais volume. Precisa de ARQUITETURA que transforme 25 anos de excelência em patrimônio escalável. Marca pessoal, programa premium, ativo digital. CPP é a engenharia que falta — sem trair sua identidade técnico-discreta.",
        },
        "plano_acao": [
            {
                "fase": "30 dias",
                "titulo": "Capturar valor que já entrega",
                "acoes": [
                    "Subir consulta de R$ 480 para R$ 800-1.200 (coerente com IRCAD + Lübeck)",
                    "Reescrever bio + site em torno de UMA promessa: 'Coloproctologista referência regional treinado em IRCAD Strasbourg e Lübeck'",
                    "Capturar depoimento em vídeo das próximas 10 colonoscopias e 5 cirurgias eletivas — banco premium de prova social",
                    "Reduzir convênios IPÊ progressivamente (manter Unimed por enquanto)",
                ],
            },
            {
                "fase": "60 dias",
                "titulo": "Estruturar produto premium",
                "acoes": [
                    "Programa 'Saúde Colorretal Premium' — screening completo + colonoscopia + acompanhamento + cirurgia eletiva quando indicada · ticket pacote R$ 12-22k",
                    "Captação inversa: deixar de competir com Vale dos Sinos local e atrair pacientes de POA, Caxias, Pelotas",
                    "Newsletter mensal pra gastros + médicos família da região (referenciamento qualificado)",
                    "Site próprio premium (substituir Wix) com identidade visual coerente",
                ],
            },
            {
                "fase": "90 dias",
                "titulo": "Construir além de você",
                "acoes": [
                    "Recrutar 1-2 coloproctologistas júnior pra escalar volume mantendo o nome como marca-mãe",
                    "Lançar mentoria/curso pra coloproctologistas que querem migrar pra videolaparoscopia avançada (replicar IRCAD/Lübeck)",
                    "Estruturar Endosinos como marca institucional — sociedade societária + sucessão",
                    "Retomar produção científica · 1 paper/ano + capítulo de livro pra fortalecer autoridade",
                ],
            },
        ],
    },

    # ===== 3 · 13h · Paulo Victor de Souza Pereira =====
    {
        "slug": "paulo-victor-pereira",
        "ordem": 3,
        "hora": "13:00",
        "zoom": "https://us06web.zoom.us/j/88042216514",
        "nome": "Dr. Paulo Victor de Souza Pereira",
        "nome_lista": "Dr Paulo Victor Pereira",
        "correcao_grafia": None,
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Cirurgia do Pé e Tornozelo · Medicina da Dor · Ortopedia Geral",
        "cidade": "Brasília",
        "estado": "DF",
        "crm": "CRM-DF 22186 · RQE 17862",
        "formacao": [
            "Especialista em Ortopedia e Traumatologia · RQE 17862",
            "Subespecialização em Cirurgia do Pé e Tornozelo",
            "Operador clínico-cirúrgico (sem Lattes, sem PubMed)",
        ],
        "estruturas": [
            "ICOD — Instituto da Coluna Vertebral, Ortopedia, Dor e Otorrino · Águas Claras (Albany Medical Center)",
            "ICOD Paranoá — atendimento popular",
            "Sócio fundador da ICOD desde 2018 (CNPJ 30.599.744/0001-35) · 10 sócios",
        ],
        "credenciais": [
            "Doctoralia: 151 avaliações verificadas · média 5 estrelas",
            "7 anos como sócio fundador de clínica multidisciplinar ortopédica",
            "2 endereços: Águas Claras (premium) + Paranoá (popular)",
            "Aceita 54+ convênios — Postal Saúde, Camed, Saúde Caixa (Brasília funcionalismo público federal)",
        ],
        "instagram": None,
        "instagram_url": None,
        "instagram_aberto": False,
        "instagram_seguidores": None,
        "instagram_posts": None,
        "instagram_bio": "[sem perfil pessoal · só @clinicaicod institucional]",
        "instagram_tom": "Ausente como marca pessoal · presença 100% institucional",
        "site": "https://icod.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/paulo-victor-de-souza-pereira/ortopedista-traumatologista/aguas-claras",
        "linkedin": None,
        "tagline_atual": "[sem narrativa pública pessoal · diluído na ICOD]",
        "posicionamento_atual_publico": "Ortopedista de pé e tornozelo dentro da ICOD em Águas Claras/Brasília — reputação técnica cravada via Doctoralia (151 reviews 5⭐) mas voz própria ainda dentro da marca dos 10 sócios. **Segunda call CPP em 2 dias.**",
        "potencial_publico": "Paulo Victor, ontem a gente conversou e você ouviu. Hoje voltamos com o aprofundamento. <strong>O ativo que você tem (151 reviews 5 estrelas em 7 anos) precisa virar marca individual.</strong> A ICOD continua sendo seu ativo institucional. O que falta é o 'Dr. Paulo Victor' como marca paralela — autoridade individual que pode coexistir, mas que cobra pelo seu nome.",
        "perfil_cpp": "GAVIÃO em transição (com aroma de Pato residual)",
        "score_compra": None,
        "perfil_evidencias": [
            "Pagou R$1.000 sinal · 2ª call CPP = sinal forte de busca por sistema",
            "Sócio fundador ICOD 7 anos = entendeu o jogo do negócio",
            "151 reviews 5⭐ Doctoralia = autoridade clínica cravada",
            "MAS R$350 consulta + 54+ convênios = subprecificação clássica",
            "Sem Instagram pessoal, sem site próprio, sem LinkedIn = invisível como marca individual",
        ],
        "dores_top3": [
            ("Convênio com ticket comprimido", "54+ planos aceitos + R$350 num condomínio premium de Águas Claras. Postal/Camed/Saúde Caixa = funcionalismo público de Brasília."),
            ("Diluição dentro da sociedade ICOD", "10 sócios numa marca posicionada genericamente. Ele é invisível dentro da própria clínica que ajudou a fundar."),
            ("Sem marca pessoal", "Em 2026, sem Instagram, sem site, sem LinkedIn. Provável crença: 'Doctoralia + boca-a-boca basta'. É exatamente a crença que CPP quebra."),
        ],
        "gaps": [
            ("Sem nicho dentro do nicho", "'Pé e tornozelo' é amplo. Não comunica se foca hálux valgo? esporão? lesão esportiva? pé diabético?"),
            ("Sem prova social fora do Doctoralia", "151 reviews só na plataforma. Não converte para particular premium em Águas Claras."),
            ("Sem produto próprio / jornada", "Consulta avulsa CBHPM. Sem pacote, programa, jornada de tratamento. Modelo Pato dentro de estrutura Gavião."),
        ],
        "hooks_abertura": [
            "Paulo Victor, ontem a gente conversou e você confirmou tudo que eu já tinha mapeado. Hoje a pergunta é: o que você fez nas últimas 24h pra começar a construir o 'Dr. Paulo Victor' como marca paralela?",
            "151 reviews 5 estrelas no Doctoralia é um ativo absurdo. Mas você não capturou nem um depoimento em vídeo desses pacientes. Por quê?",
            "Você é o único de pé e tornozelo entre os 10 sócios. Isso é vantagem competitiva sub-aproveitada. Vamos cravar nicho hoje?",
        ],
        "objecoes_esperadas": [
            "'Brasília tem cultura de funcionalismo público — paciente quer usar Postal/Camed'",
            "'Eu não preciso de Instagram, meu Doctoralia me trouxe 151 reviews'",
            "'Como saio da marca ICOD se ajudei a construir e tenho 9 sócios?'",
        ],
        "abordagem_recomendada": "Continuação do diagnóstico de ontem. Tom de pares acelerando. Patrick: validar 151 reviews + 7 anos de ICOD como ativos. Mateus: trazer caso prático de cirurgião que construiu marca paralela à clínica. Mostrar como cirurgião premium em Brasília cobra R$ 1.500 consulta + R$ 80-120k cirurgia mantendo participação na clínica.",
        "alerta_homonimo": "97% confiança · CRM-DF 22186 + RQE 17862 + sócio CNPJ ICOD + Doctoralia + DDD 61 — confirmado ontem.",
        "fontes": [
            "https://www.doctoralia.com.br/paulo-victor-de-souza-pereira/ortopedista-traumatologista/aguas-claras",
            "https://icod.com.br/",
            "https://cnpj.biz/30599744000135",
        ],
        "pre_diagnostico": {
            "frase_central": "Caso de sucesso clínico que ainda não virou negócio. Reputação cravada (151 reviews 5⭐), marca individual zerada.",
            "pontos": [
                "7 anos como sócio fundador da ICOD = você dividiu a marca por 10 antes de construir a sua.",
                "151 avaliações 5⭐ no Doctoralia provam que o paciente que chega adora. Mas o paciente premium nem chega — porque não te encontra fora do Doctoralia.",
                "R$350 a consulta em Águas Claras + 54 convênios aceitos = ticket de funcionalismo público num bairro premium.",
                "Sem Instagram pessoal, sem site próprio, sem LinkedIn em 2026. Sua marca pessoal está dentro de @clinicaicod, junto com 9 outros sócios.",
            ],
            "no_central": "A ICOD continua sendo seu ativo. O que falta é construir o 'Dr. Paulo Victor' como marca paralela e complementar — autoridade individual que pode coexistir com a sociedade, mas que cobra pelo seu nome.",
        },
        "plano_acao": [
            {
                "fase": "30 dias",
                "titulo": "Sair do anonimato",
                "acoes": [
                    "Eleger sub-nicho dentro de pé/tornozelo (esportivo? hálux valgo? pé do diabético? performance?)",
                    "Abrir Instagram pessoal com bio cravando o sub-nicho",
                    "Pedir review no Doctoralia para pacientes pessoais (separar da marca ICOD)",
                ],
            },
            {
                "fase": "60 dias",
                "titulo": "Construir marca pessoal paralela",
                "acoes": [
                    "Site próprio (drpaulovictor.com.br) com proposta clara — paralelo à ICOD, não conflitante",
                    "Subir ticket particular de R$ 350 para R$ 800-1.200",
                    "Pacote premium pro sub-nicho escolhido (R$ 18-28k jornada)",
                ],
            },
            {
                "fase": "90 dias",
                "titulo": "Sair dos convênios diluentes",
                "acoes": [
                    "Reduzir convênios aceitos de 54 para 5-10 (manter ticket alto, sair de Postal/Camed/Saúde Caixa)",
                    "Parcerias com clubes esportivos, academias premium, lojas de corrida em Brasília",
                    "Conteúdo segmentado pro paciente Águas Claras/Lago Sul",
                ],
            },
        ],
    },

    # ===== 4 · 15h · Ildo Valter Golff Filho =====
    {
        "slug": "ildo-golff",
        "ordem": 4,
        "hora": "15:00",
        "zoom": "https://us06web.zoom.us/j/82529974512",
        "nome": "Dr. Ildo Valter Golff Filho",
        "nome_lista": "Dr Ildo Golff",
        "correcao_grafia": None,
        "especialidade": "Neurocirurgia",
        "subespecialidade": "Neurocirurgia Geral · Preceptor",
        "cidade": "Cascavel",
        "estado": "PR",
        "crm": "CRM-PR 40772",
        "formacao": [
            "Bacharel em Ciências Contábeis · Univel (União Educacional de Cascavel) · 2010",
            "Graduação Medicina · FAG (Centro Universitário Fundação Assis Gurgacz · 2013-2018)",
            "Estágio Clínica Médica · HUOP (Hospital Universitário do Oeste do Paraná, Unioeste) · 2015/16",
            "Residência Neurocirurgia (5 anos) · Hospital Universitário Cajuru · PUC-PR · Curitiba (2019-2024)",
            "Co-autor 'Correlation between Profile of Intracranial Hemorrhages and GOS at Discharge' · J. Neurology Research Reviews 2024",
            "Trabalho de graduação 'Aderência à Insulinoterapia em Diabetes Mellitus tipo 1' · THEMA ET SCIENTIA 2017",
        ],
        "estruturas": [
            "Hospital São Lucas Cascavel · preceptor adjunto da Neurocirurgia · R. Eng. Rebouças 2219",
            "Pronto Atendimento de Santa Helena/PR · 20h/sem como clínico (renda complementar SUS)",
            "Clínica Médica Dr. Golff Ltda · CNPJ 32.253.406/0001-72 · fundada 13/12/2018 · Rua Santa Catarina 1947 · Centro Cascavel · capital R$ 5 mil",
            "Sócios da clínica: Ildo Valter Golff Filho + Willyan Hardt Golff (irmão · provavelmente médico também)",
        ],
        "credenciais": [
            "**Bacharel em Ciências Contábeis ANTES da Medicina** — única combinação rara entre cirurgiões",
            "5 anos de residência PUC-PR Cajuru (referência neurocirurgia PR)",
            "Preceptor adjunto Hospital São Lucas Cascavel",
            "Filiação SBN Sociedade Brasileira de Neurocirurgia",
            "FAG egresso (alma mater da turma TXVII / 'Cássio Franco')",
        ],
        "instagram": None,
        "instagram_url": None,
        "instagram_aberto": False,
        "instagram_seguidores": None,
        "instagram_posts": None,
        "instagram_bio": "[handle não-óbvio ou perfil privado · território digital virgem]",
        "instagram_tom": "Inexistente publicamente · cirurgião novo (38 anos · saiu da residência em 2024) · zero estratégia digital construída",
        "site": None,
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": None,
        "posicionamento_atual_publico": "Neurocirurgião recém-formado pela PUC-PR Cajuru · preceptor adjunto Hospital São Lucas Cascavel · com formação contábil prévia (Univel 2010) que o torna o cirurgião que sabe ler DRE sozinho. Família tradicional Cascavel · pai economista/perito judicial.",
        "potencial_publico": "Ildo, você é provavelmente o único cirurgião do Brasil que sabe ler um DRE sem precisar do contador traduzir. Bacharel em Contábeis ANTES de fazer Medicina. <strong>Você entende que medicina é empresa</strong> desde a graduação — e voltou pra Cascavel pra fincar bandeira. O que falta não é ambição, é mapa.",
        "perfil_cpp": "GAVIÃO",
        "score_compra": 72,
        "perfil_evidencias": [
            "**Bacharel em Ciências Contábeis (Univel 2010) + Medicina (FAG 2018)** — vantagem competitiva única",
            "5 anos de residência PUC-PR Cajuru (referência neurocirurgia PR)",
            "Preceptor adjunto Hospital São Lucas Cascavel desde 2024-2025",
            "Pai economista/perito judicial TRT9 · 146 processos como perito · família tradicional Cascavel",
            "Pagou R$1k sinal · 38 anos · momento exato de transição residente → empresário particular",
        ],
        "dores_top3": [
            ("Renda baixa pós-residência", "Pronto-atendimento Santa Helena 20h/sem como clínico = sintoma clássico de neurocirurgião novo que precisa de fluxo. Volta pra Cascavel mas ainda não estruturou agenda particular."),
            ("Capital social subdimensionado", "Clínica Dr. Golff Ltda capital R$ 5 mil = casca corporativa, não empresa real. Compartilha endereço com escritório do pai (Av. Paraná 3035 · Rua Santa Catarina 1947)."),
            ("Território digital virgem", "Sem Instagram profissional, sem Doctoralia, sem site, sem reviews. Cascavel inteira não te conhece ainda. 5 anos de PUC-PR e zero capital de marca."),
        ],
        "gaps": [
            ("Sem identidade digital", "Zero footprint indexado. Quem busca 'neurocirurgião Cascavel' não te encontra. Vácuo de mídia (zero Catve/CGN) é território livre."),
            ("Sem nicho declarado", "Neurocirurgia geral em Cascavel concorre com Curitiba (1h45 de carro). Falta aresta única — coluna minimamente invasiva? Tumor cerebral? Funcional? Pediátrica?"),
            ("Refém potencial da Unimed", "Cascavel = Unimed-mente refém. Quem trava na Unimed escala paciente, não margem."),
        ],
        "hooks_abertura": [
            "Você é o único cirurgião do Brasil que sabe ler um DRE sem precisar do contador traduzir. Isso não é hobby — é vantagem competitiva única.",
            "Seu pai é perito judicial há décadas em Cascavel — você cresceu vendo cálculo, processo, retaguarda. Falta empacotar isso em consultório de R$ 800 a sessão.",
            "Você fez 5 anos em Curitiba para voltar. Não voltou pra ser plantonista em Santa Helena 20h por semana.",
            "O Hospital São Lucas te bota como preceptor — você JÁ é autoridade local. Falta autoridade DIGITAL. Cascavel inteira não te conhece ainda.",
            "Você é o filho que herdou o pai contador-perito + virou médico de elite. CPP é a engenharia que falta: posicionamento, oferta, funil. Você junta tudo num único negócio que vale 10× o consultório atual.",
        ],
        "objecoes_esperadas": [
            "'Estou recém-formado, preciso construir base de pacientes primeiro'",
            "'Cascavel não paga ticket de neurocirurgião premium'",
            "'Unimed Cascavel domina o mercado · não dá pra fugir do convênio'",
            "'Eu prefiro o consultório técnico ao palco'",
        ],
        "abordagem_recomendada": "Tom de pares (não 'aprenda do zero'). Patrick: usar a CONTABILIDADE como gancho ouro — 'você é o cara que sabe que medicina é empresa'. Mateus: trazer caso de neurocirurgião CPP do interior que escalou ticket. Provocar: 'Você fez 5 anos em Curitiba pra voltar, não pra ser plantonista'. CPP é a engenharia de empresa pra quem JÁ pensa como empresário mas opera como funcionário.",
        "alerta_homonimo": "100% confiança · CRM-PR 40772 + Univel 2010 + FAG 2018 + Cajuru 2024 + Hospital São Lucas Cascavel · cruzamento Escavador + Jusbrasil + CNPJ.",
        "fontes": [
            "https://www.escavador.com/sobre/5740323/ildo-valter-golff-filho",
            "https://www.escavador.com/sobre/16191524/ildo-valter-golff",
            "https://www.jusbrasil.com.br/processos/nome/93115306/perito-ildo-valter-golff",
            "https://cnpj.biz/32253406000172",
            "https://cliniguia.com/profissionais/ildo-valter-golff-filho-700209910650927/",
            "https://fhsl.org.br/pesquisaMedico",
            "https://fag.edu.br/noticia/18006",
        ],
        "pre_diagnostico": {
            "frase_central": "Você é o cirurgião que pensa como empresário antes de operar. Falta a engenharia de marca que transforme essa cabeça única em ativo monetizável.",
            "pontos": [
                "Bacharel em Ciências Contábeis (Univel 2010) ANTES de Medicina (FAG 2018) + 5 anos de residência PUC-PR Cajuru = combinação raríssima.",
                "Pai economista/perito TRT9 com 146 processos como perito · família tradicional Cascavel · você compartilha endereço comercial com ele.",
                "Mas: 38 anos · pronto-atendimento Santa Helena 20h/sem · capital clínica R$ 5k · zero Instagram · zero Doctoralia · zero reviews.",
                "Cascavel é dominada pela Unimed (17 hospitais, 613 médicos cooperados). Quem não credencia, não fatura volume — mas margem alta só em particular.",
            ],
            "no_central": "Você não precisa aprender que medicina é empresa — você JÁ sabe. Precisa de método pra estruturar o consultório premium que o seu currículo merece. CPP é engenharia, não conteúdo.",
        },
        "plano_acao": [
            {
                "fase": "30 dias",
                "titulo": "Sair da invisibilidade",
                "acoes": [
                    "Abrir Instagram profissional (@drildogolff ou similar) — bio: 'Neurocirurgião · Hospital São Lucas Cascavel · Preceptor PUC-PR'",
                    "Cadastrar Doctoralia + BoaConsulta + Google Meu Negócio",
                    "30 posts em 30 dias com casos clínicos comentados (com consentimento) + temas educativos (cefaleia, dor lombar, hérnia)",
                    "Subir capital social da clínica · estruturar empresa de verdade (não casca de R$ 5k)",
                ],
            },
            {
                "fase": "60 dias",
                "titulo": "Construir oferta premium",
                "acoes": [
                    "Eleger sub-nicho — coluna minimamente invasiva? Tumor cerebral? Funcional?",
                    "Plano de saída gradual da Unimed (-30% volume convênio em 90 dias)",
                    "Site próprio (drildogolff.com.br) com programa, jornada, depoimentos",
                    "Plano de saída gradual do PA Santa Helena · concentrar foco em cirurgia particular",
                ],
            },
            {
                "fase": "90 dias",
                "titulo": "Virar referência regional",
                "acoes": [
                    "Mídia local Cascavel (Catve, CGN, Tribuna PR) + podcasts de saúde regional",
                    "Captação de paciente premium do oeste PR (Toledo, Foz do Iguaçu, Marechal Cândido Rondon)",
                    "Telemedicina e segunda opinião pra interior PR · ampliar geografia",
                    "Estruturar Clínica Dr. Golff como negócio familiar (irmão Willyan Hardt Golff sócio + pai como retaguarda contábil)",
                ],
            },
        ],
    },

    # ===== 5 · 17h · Vítor Vilhegas =====
    {
        "slug": "vitor-vilhegas",
        "ordem": 5,
        "hora": "17:00",
        "zoom": "https://us06web.zoom.us/j/81319135478",
        "nome": "Dr. Vítor Augusto Baptista Vilhegas",
        "nome_lista": "Dr Vitor Vilhegas",
        "correcao_grafia": None,
        "especialidade": "Ortopedia e Traumatologia",
        "subespecialidade": "Cirurgia do Joelho · Prótese Unicompartimental com Navegação Intra-operatória",
        "cidade": "Adamantina",
        "estado": "SP",
        "crm": "CRM-SP 170724 · RQE 98735",
        "formacao": [
            "Graduação Medicina · UNOESTE Universidade do Oeste Paulista · Pres. Prudente",
            "Residência Ortopedia e Traumatologia · Santa Casa de Misericórdia de Ourinhos-SP",
            "Especialização Cirurgia do Joelho · Ortocity (São Paulo capital) · grupo SBCJ certificado · 16 cirurgiões · ~700 cirurgias/ano",
            "Sem Lattes ativo · sem PubMed",
        ],
        "estruturas": [
            "Consultório próprio · Av. Rio Branco 61 · Centro Adamantina-SP (CEP 17800-000)",
            "Santa Casa de Adamantina (CNES 2077647) · 35+ especialidades · principal hospital geral da cidade",
            "Atendimento secundário · Instituto de Cardiologia Adamantina",
            "Mudança recente de consultório (Reel IG: 'Estamos de casa nova!')",
        ],
        "credenciais": [
            "**PIONEIRO REGIONAL · primeira cirurgia de prótese unicompartimental de joelho com NAVEGAÇÃO INTRA-OPERATÓRIA da região** (Siga Mais 21/07/2025 · Adamantina · Lucélia)",
            "Trouxe Dr. Álvaro Souto (Dourados-MS) como cirurgião convidado · investimento técnico pioneiro",
            "Família Vilhegas · sobrenome de origem espanhola Toledo · linhagem D. Diogo Ortiz · brasão com dois braços armados",
            "Pai/tio Sérgio Vilhegas · odontólogo · professor UNOESTE Pres. Prudente · especializado em Ortodontia/Ortopedia Facial",
            "Provável irmão Dr. João Paulo Vilhegas · dentista Pres. Prudente",
            "Praticamente monopólio do joelho em Adamantina · lista 'Top 10 ortopedistas' BoaConsulta",
        ],
        "instagram": "@drvitorvilhegas",
        "instagram_url": "https://www.instagram.com/drvitorvilhegas/",
        "instagram_aberto": True,
        "instagram_seguidores": "—",
        "instagram_posts": "—",
        "instagram_bio": '"Dr. Vítor Vilhegas · Ortopedista · Cirurgia do Joelho · Adamantina-SP" · drvitorvilhegas.com.br',
        "instagram_tom": "Médico premium em construção · investiu em equipamento (navegação intra-operatória) e em marketing (site + IG + FB) · faz por intuição, ainda sem sistema",
        "site": "https://drvitorvilhegas.com.br/",
        "doctoralia": None,
        "linkedin": None,
        "tagline_atual": '"Ortopedia · Cirurgia do Joelho · Adamantina"',
        "posicionamento_atual_publico": "Ortopedista joelho de Adamantina-SP que voltou a Pres. Prudente pra construir nome próprio. Fellowship Ortocity-SP. Em julho/2025 foi pioneiro regional em prótese unicompartimental com navegação intra-operatória. Família Vilhegas (linhagem nobre espanhola) de Pres. Prudente — pai/tio Sérgio Vilhegas, dentista UNOESTE.",
        "potencial_publico": "Vítor, você fez Ortocity. A diferença entre você e o clínico de Adamantina não é a técnica — é como você conta a história. Em julho de 2025 você foi pioneiro regional em navegação intra-operatória de joelho. <strong>Isso é OURO de marketing — e tenho quase certeza que rendeu uma matéria local e morreu ali.</strong> Em Adamantina + região, isso vira filme de 30 segundos por mês durante 1 ano.",
        "perfil_cpp": "GAVIÃO",
        "score_compra": None,
        "perfil_evidencias": [
            "Fellowship Ortocity-SP · joelho premium · grupo SBCJ certificado",
            "Pioneiro regional em navegação intra-operatória de prótese de joelho (julho/2025)",
            "Casa nova de consultório · investimento físico · ambição de upgrade",
            "Site próprio + IG ativo + FB + presença em portais médicos",
            "Pagou R$1.097 mesmo morando em Adamantina (35k hab) = sinal forte de fome",
            "Família Vilhegas (linhagem nobre + tradição odontologia Pres. Prudente) = capital simbólico",
        ],
        "dores_top3": [
            ("Teto de Adamantina (35k hab)", "Por melhor que seja, só a cidade não sustenta cirurgia de joelho premium contínua. Precisa drenar Lucélia, Osvaldo Cruz, Dracena, Mariápolis, Pacaembu, Pres. Prudente."),
            ("Pioneirismo não capitalizado", "Cirurgia da prótese unicompartimental com navegação foi a primeira da região. Rendeu UMA matéria local em 2025 e morreu. Material gigante de marketing nunca foi convertido em filme/funil/conteúdo."),
            ("Refém da Santa Casa + convênios", "Provavelmente está fazendo fluxo via Santa Casa de Adamantina. Convênio paga R$X · particular paga 8X pelo mesmo procedimento. Mix particular vs convênio precisa ser auditado."),
        ],
        "gaps": [
            ("Sem método estruturado de marketing", "Investiu em peças (site + IG + FB + casa nova) mas sem método. Faz por intuição. A diferença entre intuição e método são 3x no ticket médio."),
            ("Sem narrativa de marca pessoal", "Família Vilhegas tem peso em Pres. Prudente. Foi pra Adamantina construir nome próprio. Mas a história ainda não foi contada — 'O Vilhegas do joelho da Nova Alta Paulista'."),
            ("Sem captação regional ampla", "Adamantina (35k) precisa drenar paciente de raio 100km. Sem mapeamento, sem mídia regional dirigida, sem parcerias estratégicas."),
        ],
        "hooks_abertura": [
            "Você fez Ortocity. Sabe o que separa quem fez fellowship em SP do clínico de Adamantina? Não é a técnica — é como você conta a história. Hoje, na sua cidade, todo mundo sabe que você opera. Quase ninguém sabe POR QUE você é diferente.",
            "A cirurgia da prótese unicompartimental com navegação foi a primeira da região. Isso é OURO de marketing — e tenho quase certeza que rendeu uma matéria local e morreu ali. Em Adamantina + região, isso vira filme de 30 segundos por mês durante 1 ano.",
            "Adamantina tem 35 mil habitantes. Você precisa de 10 cirurgias premium/mês — não dá pra esperar elas baterem na porta. O jogo é drenar Lucélia, Pacaembu, Osvaldo Cruz, Dracena. Você já mapeou seu raio de captação?",
            "Família Vilhegas tem peso em Pres. Prudente — seu pai/tio é referência na odontologia de lá. Você foi pra Adamantina construir nome próprio. Faz quanto tempo? E você já é 'O Vilhegas do joelho' na região, ou ainda 'o filho do Sérgio'?",
            "Casa nova do consultório, navegação pioneira, site próprio, IG ativo — você JÁ está jogando o jogo de marca. Mas eu aposto que está fazendo isso por intuição, não por sistema. A diferença entre intuição e método são 3x no ticket médio.",
            "Em Adamantina, você é praticamente monopólio do joelho. Isso é poder de precificação que NENHUM ortopedista da capital tem. Mas só funciona se o paciente sair convencido que você É O CARA — não 'um cara'.",
        ],
        "objecoes_esperadas": [
            "'Adamantina é cidade pequena, não cabe ticket de capital'",
            "'Já tenho marketing, é só amplificar — não preciso de método'",
            "'Particular vs convênio · paciente quer usar plano'",
            "'Família é referência em Pres. Prudente · não quero entrar na sombra deles'",
        ],
        "abordagem_recomendada": "Tom de pares acelerando. Vítor JÁ é Gavião com capital simbólico (família Vilhegas). Patrick: validar Ortocity + pioneirismo navegação como ativos · provocar 'pioneiro regional rendeu UMA matéria e morreu — vamos transformar em campanha'. Mateus: trazer caso de cirurgião joelho do interior CPP que escalou. CPP transforma intuição em método.",
        "alerta_homonimo": "100% confiança · CRM-SP 170724 + RQE 98735 + Adamantina + Santa Casa Adamantina + drvitorvilhegas.com.br + Siga Mais 21/07/2025.",
        "fontes": [
            "https://drvitorvilhegas.com.br/",
            "https://www.instagram.com/drvitorvilhegas/",
            "https://www.sigamais.com/noticias/saude/santa-casa-de-adamantina-realiza-cirurgia-de-prntese-unicompartimental-de-joelho-inndita-na-regino/",
            "https://consultaespecialista.com.br/dr-vitor-vilhegas/",
            "https://www.ortocity.com.br/estagio-de-joelho/",
            "https://www.unoeste.br/graduacao/InfoDocente/8510",
        ],
        "pre_diagnostico": {
            "frase_central": "Você está a 1-2 movimentos de virar referência inquestionável da Nova Alta Paulista em joelho. Falta sistema.",
            "pontos": [
                "Fellowship Ortocity-SP + pioneirismo regional em navegação intra-operatória + casa nova de consultório + site + IG + FB = você JÁ entendeu que precisa marketing.",
                "Família Vilhegas (linhagem nobre + tradição odontologia Pres. Prudente · pai/tio Sérgio Vilhegas UNOESTE) = capital simbólico que pode ser amplificado.",
                "Adamantina (35k hab) é praticamente monopólio do joelho · 'Top 10 ortopedistas' regional · poder de precificação que ortopedista de capital não tem.",
                "Mas: pioneirismo da navegação rendeu UMA matéria local em 2025 e morreu. Investimento técnico não foi convertido em campanha de marketing sistemática.",
            ],
            "no_central": "Você não precisa de mais técnica nem de mais peças de marketing. Precisa de método que transforme cada movimento técnico (Ortocity, navegação, casa nova) em campanha multi-touch que drene região inteira.",
        },
        "plano_acao": [
            {
                "fase": "30 dias",
                "titulo": "Capitalizar o que já existe",
                "acoes": [
                    "Capturar 1 ano inteiro de conteúdo a partir do pioneirismo da navegação · 12 ângulos diferentes (técnica · paciente · equipe · resultado · região)",
                    "Bio: 'Dr. Vítor Vilhegas · Cirurgião de Joelho · Pioneiro regional em navegação · Adamantina + região'",
                    "Mapear raio de captação 100km · Lucélia, Osvaldo Cruz, Dracena, Pacaembu, Mariápolis, Pres. Prudente",
                    "Subir consulta avaliativa pra R$ 600-1.000",
                ],
            },
            {
                "fase": "60 dias",
                "titulo": "Estruturar oferta premium",
                "acoes": [
                    "Pacote 'Programa Joelho Premium · Avaliação + Cirurgia + Recuperação' · ticket único R$ 25-45k",
                    "Auditar mix particular vs convênio · plano de saída gradual",
                    "Parcerias com clubes esportivos, academias, lojas de corrida da Nova Alta Paulista",
                    "Site próprio premium com casos pioneiros + depoimentos em vídeo",
                ],
            },
            {
                "fase": "90 dias",
                "titulo": "Virar referência regional",
                "acoes": [
                    "Mídia regional · Folha de Adamantina, Tribuna do Vale, Diário do Pontal, Folha SJRP",
                    "Parceria com cirurgião convidado mensal (replicar modelo Álvaro Souto Dourados)",
                    "Telemedicina + segunda opinião pra raio 200km",
                    "Posicionar 'Vilhegas do joelho' como categoria pessoal — não 'o filho do Sérgio'",
                ],
            },
        ],
    },

    # ===== 6 · 18h · Alander Sobreira Vanderlei =====
    {
        "slug": "alander-sobreira",
        "ordem": 6,
        "hora": "18:00",
        "zoom": "https://us06web.zoom.us/j/83674412471",
        "nome": "Dr. Alander Sobreira Vanderlei",
        "nome_lista": "Dr Alander Sobreira",
        "correcao_grafia": None,
        "especialidade": "Neurocirurgia",
        "subespecialidade": "Coluna minimamente invasiva (MIS) · Crânio",
        "cidade": "Fortaleza",
        "estado": "CE",
        "crm": "CRM-CE 10374 · RQE 6258",
        "formacao": [
            "Graduação · Faculdade de Medicina de Juazeiro do Norte (FMJ) · 2006",
            "TCC: 'Protocolo de Status Epilepticus' · orientação Prof. José Christian Machado Ximenes",
            "Residência Neurocirurgia · Hospital Municipal Odilon Behrens · Belo Horizonte/MG",
            "Fellowship · Rush University Medical Center · Chicago/USA · Coluna Minimamente Invasiva (MIS)",
            "Trilíngue: Português · Inglês · provável Espanhol",
            "13 anos atuando em Fortaleza desde 2013",
        ],
        "estruturas": [
            "Coordenador de Neurocirurgia · Rede OTO Kora · Hospital Oto Aldeota · Av. Antônio Sales 990 · Fortaleza",
            "Atende em 2 cidades: Fortaleza + Sobral · rota interior + capital",
            "Endereço Rua Monsenhor Bruno 2332 · Fortaleza",
            "Parceria operatória documentada com Dr. João Paulo de Vasconcelos Mattos (neurocirurgião FOR)",
        ],
        "credenciais": [
            "**Fellowship Rush University Chicago em Coluna MIS** — credencial americana raríssima em Fortaleza",
            "Coordenador de Neurocirurgia OTO Kora desde 2014 · 12 anos de liderança institucional",
            "Palestrante 9º Congresso Cearense de Neurologia e Neurocirurgia (NeuroCeará 2025)",
            "Membro Sociedade Brasileira de Neurocirurgia (SBN)",
            "Comentarista de saúde pública na BAND-CE (artigos sobre Parkinson)",
            "@dralandersobreira · 28.000 seguidores · 435 posts · cristão público",
            "Frase-âncora pública (24/12/2025): 'Quando a técnica alcança seu limite, é a graça que sustenta'",
        ],
        "instagram": "@dralandersobreira",
        "instagram_url": "https://www.instagram.com/dralandersobreira/",
        "instagram_aberto": True,
        "instagram_seguidores": "28.000",
        "instagram_posts": "435",
        "instagram_bio": '"Neurocirurgião especializado em crânio e coluna vertebral. CRM-CE 10374, RQE 6258. Contato 981400077."',
        "instagram_tom": "Médico-pastor · não é influencer-de-Maybach · humanizado, didático, NÃO performático · linguagem cristã evangélica · gratidão > militância",
        "site": "https://www.dralandersobreira.com.br/",
        "doctoralia": "https://www.doctoralia.com.br/alander-sobreira-vanderlei",
        "linkedin": None,
        "tagline_atual": '"Neurocirurgião · Crânio e Coluna"',
        "posicionamento_atual_publico": "Neurocirurgião de Fortaleza · fellowship Rush Chicago em Coluna MIS · Coordenador OTO Kora desde 2014 · 28.000 seguidores · cristão público · trajetória interior→cima (FMJ Juazeiro → Behrens BH → Rush Chicago → Fortaleza+Sobral).",
        "potencial_publico": "Alander, 28k no IG e Rush Chicago no currículo — você tem o ativo mais raro de Fortaleza, mas no Doctoralia não tem nem review. <strong>Você é Rush cobrando preço de Ceará.</strong> O problema não é técnica — é permissão. CPP entrega exatamente o que você precisa: virar referência nacional sem trair seu posicionamento de médico-servo.",
        "perfil_cpp": "ÁGUIA",
        "score_compra": 84,
        "perfil_evidencias": [
            "Rush University Chicago em Coluna MIS = credencial americana raríssima",
            "13 anos de OTO Kora · Coordenador desde 2014 · liderança institucional",
            "@dralandersobreira 28k seguidores · 435 posts · 64 seg/post (engajamento real)",
            "Cristão público confirmado · frase 24/12/2025 · âncora identitária central",
            "Palestrante NeuroCeará 2025 · referência regional reconhecida",
            "Fortaleza + Sobral = rota interior+capital · cobertura ampla",
            "Pagou R$1k mesmo sendo Águia consolidada = sinal forte de busca de próximo patamar",
        ],
        "dores_top3": [
            ("Capital subaproveitado · Doctoralia VAZIA", "13 anos de prática · 28k IG · Rush Chicago — e zero reviews públicas no Doctoralia. 'Avaliações em breve'. Capital social do paciente não capturado digitalmente."),
            ("Cobrança incoerente com o repertório", "Você opera o que 95% dos neuros do Nordeste mandam pra São Paulo. Por que ainda cobra preço de Ceará? Permissão pra cobrar como Rush não foi internalizada."),
            ("Sem produto / livro / curso · autoridade vazando", "435 posts e zero curso, zero livro, zero produto. Rush + 28k = barril de pólvora não acendido. Em 12 meses pode ter livro de Coluna MIS e ser referência nacional."),
        ],
        "gaps": [
            ("Doctoralia VAZIA", "Sem reviews públicas após 13 anos. Pode ter centenas de pacientes felizes e zero capital social capturado em plataforma."),
            ("Zero PubMed", "Cabeça técnica que não converteu em produção científica. Fellowship Rush sem capítulo/paper publicado é fronteira aberta."),
            ("Frequência IG baixa pra perfil de 28k", "2-4 posts/mês em 2025. Plataforma sub-aproveitada · Threads tem só 3.208 seguidores."),
        ],
        "hooks_abertura": [
            "Alander, 28k no IG e Rush Chicago no currículo — você tem o ativo mais raro de Fortaleza, mas no Doctoralia não tem nem review. O que está te segurando de capitalizar?",
            "Coordenador de neuro do OTO Kora desde 2014, palestrante do NeuroCeará 2025 — você já é referência regional. Próxima fronteira é nacional. Você quer ou não quer?",
            "Li seu post de 24 de dezembro: 'tudo começa e termina em Deus, a graça é que sustenta quando a técnica alcança seu limite.' Patrick também é cristão — esse é o eixo da mentoria, não só técnica de venda.",
            "Fortaleza + Sobral, dois consultórios, Rede OTO, ICU/centro cirúrgico, agenda travada. Você está operando 13 anos como médico de elite e ainda atende como se precisasse provar. CPP é pra parar de provar.",
            "Você fellowship Rush em coluna minimamente invasiva — ou seja, opera o que 95% dos neuros do Nordeste mandam pra São Paulo. Por que você ainda cobra preço de Ceará?",
            "Você tem 435 posts e zero curso, zero livro, zero produto. Sua autoridade está vazando. Em 12 meses você pode ter um livro de coluna minimamente invasiva e ser referência nacional — não é fantasia, é matemática.",
            "Médico-servo é seu posicionamento natural. Não pede pra mudar. CPP só vai te ajudar a cobrar como Rush e atender como Cristo.",
        ],
        "objecoes_esperadas": [
            "'Eu não quero virar influencer · isso fere meu posicionamento cristão'",
            "'Já tenho 28k seguidores e fluxo bom · pra que CPP?'",
            "'Fortaleza não paga ticket de SP'",
            "'Não tenho tempo pra criar conteúdo · operar consome todo o dia'",
        ],
        "abordagem_recomendada": "Tom peer-to-peer (NUNCA 'aprenda do zero'). Patrick: ABRIR pelo eixo cristão compartilhado · validar 28k + Rush + 13 anos OTO + cristão público + palestrante NeuroCeará = autoridade que ninguém questiona. Provocar: 'Você é Rush cobrando preço de Ceará — problema não é técnica, é permissão'. Mateus: trazer caso de neurocirurgião Águia CPP que virou referência nacional sem trair posicionamento. CPP = engenharia pra cobrar como Rush e atender como Cristo.",
        "alerta_homonimo": "100% confiança · CRM-CE 10374 + RQE 6258 + FMJ Juazeiro 2006 + Behrens BH + Rush Chicago + OTO Kora + 28k IG · cruzamento perfeito.",
        "fontes": [
            "https://www.dralandersobreira.com.br/",
            "https://www.instagram.com/dralandersobreira/",
            "https://www.threads.com/@dralandersobreira",
            "https://www.facebook.com/dr.alandersobreira/",
            "https://www.escavador.com/sobre/11246480/alander-sobreira-vanderlei",
            "https://www.doctoralia.com.br/alander-sobreira-vanderlei",
            "https://neuroceara2025.com.br/programacao/",
            "https://www.catalogo.med.br/doutor/alander-sobreira-vanderlei-2551960.htm",
        ],
        "pre_diagnostico": {
            "frase_central": "Você é Rush cobrando preço de Ceará. O problema não é técnica — é permissão.",
            "pontos": [
                "FMJ Juazeiro (2006) → Hospital Odilon Behrens BH (residência) → Rush University Chicago (Coluna MIS) → Fortaleza+Sobral (13 anos) = trajetória interior→cima de quem nunca aceitou teto.",
                "Coordenador Neurocirurgia OTO Kora desde 2014 + 28.000 seguidores + Palestrante NeuroCeará 2025 + cristão público = autoridade regional consolidada que ninguém questiona.",
                "Mas: Doctoralia VAZIA · zero PubMed · zero livro · zero curso · zero produto digital. 435 posts em 28k = 64 seg/post (engajamento sólido) mas frequência baixa (2-4/mês).",
                "Você opera o que 95% dos neuros do Nordeste mandam pra São Paulo. Cobra preço de Ceará. Capital social não convertido em capital econômico.",
            ],
            "no_central": "Você não precisa de mais autoridade · você JÁ é Águia AAA. Precisa de PERMISSÃO pra cobrar coerente com seu repertório · sem trair seu posicionamento de médico-servo. CPP transforma autoridade silenciosa em autoridade reconhecida nacionalmente.",
        },
        "plano_acao": [
            {
                "fase": "30 dias",
                "titulo": "Capturar valor que já entrega",
                "acoes": [
                    "Subir ticket consulta avaliativa pra R$ 1.500-2.500 (coerente com Rush MIS)",
                    "Sistematizar captura de reviews Doctoralia · meta 50 reviews em 30 dias",
                    "Adicionar Rush University Chicago + 'Coordenador OTO Kora desde 2014' explícitos na bio do IG",
                    "Frequência IG pra 4-5 posts/semana · alternando 3 pilares (técnica + fé + saúde pública)",
                ],
            },
            {
                "fase": "60 dias",
                "titulo": "Empacotar autoridade em produto",
                "acoes": [
                    "Programa 'Coluna Premium · Avaliação MIS + Cirurgia + Recuperação' · ticket pacote R$ 35-65k",
                    "Estruturar e-book + curso online sobre Coluna Minimamente Invasiva (escala fora da agenda cirúrgica)",
                    "Newsletter mensal pra neuros + ortopedistas + médicos de família NE (referenciamento qualificado)",
                    "Captação inversa: paciente de Recife, Natal, Salvador, Belém, Manaus pra Fortaleza",
                ],
            },
            {
                "fase": "90 dias",
                "titulo": "Virar referência nacional",
                "acoes": [
                    "Lançar livro de Coluna Minimamente Invasiva (autoridade Rush convertida em produção científica)",
                    "Imersão presencial · cirurgia ao vivo pra neurocirurgiões NE",
                    "Mentoria pra neurocirurgiões cristãos (replicar trajetória interior→cima · médico-servo)",
                    "Mídia tier-1 nacional · TV + podcasts de saúde pública (BAND nacional · Globo Saúde · Você Saúde)",
                ],
            },
        ],
    },
]


# Inicial pra avatar quando não tem foto
def iniciais(nome):
    parts = [p for p in nome.replace("Dr.","").replace("Dra.","").split() if p and len(p)>1]
    if len(parts) >= 2:
        return (parts[0][0] + parts[-1][0]).upper()
    return parts[0][:2].upper() if parts else "??"
