# FBI Data — Diagnóstico CPP 07/05/2026
# Investigação profunda dos 6 cirurgiões + imagens cinematográficas 4K

BG_IMAGES = {
    "marianna-monteiro": "imagens/01-marianna-monteiro.png",
    "pitagoras-kieling": "imagens/02-pitagoras-kieling.png",
    "paulo-victor-pereira": "imagens/03-paulo-victor.png",
    "ildo-golff": "imagens/04-ildo-golff.png",
    "vitor-vilhegas": "imagens/05-vitor-vilhegas.png",
    "alander-sobreira": "imagens/06-alander-sobreira.png",
}

FBI = {
    "marianna-monteiro": {
        "quote_manifesto": "Bari Clube é nome de programa, não nome de consulta. Cadê o ticket coerente?",
        "narrativa_publica": "Você fez residência em Cirurgia Geral no HRAN, fellowship em Bariátrica sob Dr. Renato Alves Teixeira Lima (fundador do serviço de cirurgia metabólica do DF · +16.000 cirurgias) e Dr. Rafael Oliveira Galvão (coordenador SES-DF desde 2008 · +10.000 procedimentos), e em 2022 apresentou como <em>primeira autora</em> o caso 'Fístula Gastrogástrica Pós Gastroplastia em Y de Roux' no 24º Congresso Brasileiro de Cirurgia Bariátrica e Metabólica. Mas a parte mais rara não é o currículo técnico — é o que você construiu digitalmente: <em>perfil verificado azul, 10.200 seguidores, 82.100 alcançadas mensais, programa próprio nomeado (Bari Clube), movimento próprio (#BARIGAN), e funil de entrada estruturado em 7 destaques.</em> O ativo digital está montado.",
        "descobertas_publicas": [
            "<strong>CRM-DF 24276 · RQE 18912</strong> — Cirurgia Geral · Cirurgia Bariátrica e Metabólica",
            "<strong>Linhagem HRAN/SES-DF</strong> — Dr. Renato Alves Teixeira Lima (Conselheiro CRM-DF, ex-Diretor HRAN, +16 mil cirurgias) e Dr. Rafael Oliveira Galvão (criador do serviço de bariátrica SES-DF desde 2008, +10 mil procedimentos)",
            "<strong>Primeira autora SBCBM 2022</strong> — caso 'Fístula Gastrogástrica Pós Gastroplastia em Y de Roux' (poster PE-80) · co-autores Renato Teixeira + Galvão + Elias José Guedes Lima",
            "<strong>Instagram verificado azul ✓</strong> · @dra.marimonteirov · 10.200 seguidores · 397 posts · 82.100 alcançadas mensais (insights públicos)",
            "<strong>Bari Clube</strong> — programa/comunidade própria nomeada (método empacotado)",
            "<strong>#BARIGAN</strong> — movimento/categoria criada por ela (capital simbólico próprio)",
            "<strong>7 destaques estruturados em funil</strong>: CORAGEM! · Oiii · DESAFIO · Bari Clube · Comece aqui · Cirurgias Bari · #BARIGAN",
            "<strong>Bio com promessa direta de marketing</strong>: 'Te ajudo com a obesidade através do tratamento cirúrgico'",
            "<strong>Atendimento dual</strong>: Brasília (capital) + Planaltina-GO (entorno) · operação capital + entorno",
            "<strong>Mercado Brasília</strong> — uma das praças com maior poder aquisitivo do Brasil (Senado, Câmara, STF, Itamaraty, Águas Claras, Lago Sul)",
        ],
        "pitch_direcionado": [
            ("Capitalizar Bari Clube como produto premium definitivo",
             "Bari Clube é nome de programa, não nome de consulta. Definir ticket público (R$ 45-75k jornada completa) · pré-cirúrgico + cirurgia + acompanhamento 12-24m + comunidade. Hoje você cobra pela cirurgia · amanhã cobra pela transformação"),
            ("Comunicar HRAN/Renato Teixeira/Galvão na bio",
             "Sua linhagem técnica está invisível. Adicionar 'fellowship HRAN/SES-DF · linhagem Renato Teixeira/Galvão · primeira autora SBCBM 2022' = autoridade técnica alimentando autoridade digital"),
            ("Concentrar em Brasília Premium (sair de Planaltina-GO)",
             "Operação dual = ainda divide foco. Plano de saída gradual + foco em ICP servidor público federal alto-padrão (Senado, Câmara, STF, Itamaraty) e empresário Águas Claras/Lago Sul"),
            ("Escalar #BARIGAN como categoria nacional",
             "Movimento próprio existe em Brasília · falta produto digital + livro + mentoria pra outros bariátricos replicarem. #BARIGAN pode ser categoria nacional em 12-18 meses"),
        ],
        "pontos_internos": [
            "**PRINT MUDOU O DIAGNÓSTICO** · Marianna NÃO é Gavião com identidade dual (como dossiê inicial supôs) · ela é ÁGUIA em ascensão consolidada · Bari Clube + #BARIGAN + selo azul + 82k alcançadas",
            "Co-autoria SBCBM 2022 com Renato Teixeira + Galvão + Elias José Guedes Lima = linhagem HRAN confirmada",
            "82.100 alcançadas / 10.200 seguidores = está performando MAIS no algoritmo do que sua audiência captura · gargalo é conversão alcance → seguidor → paciente premium",
            "**Bari Clube** = programa próprio nomeado · sinal forte de método empacotado · sub-aproveitado em ticket público",
            "**#BARIGAN** = movimento/categoria criada por ela · capital simbólico próprio · sub-escalado nacionalmente",
            "**7 highlights em funil estruturado** (CORAGEM! · Oiii · DESAFIO · Bari Clube · Comece aqui · Cirurgias Bari · #BARIGAN) = método de Águia",
            "Sobrenome 'Vaz da Silva' tem forte presença em Goiás e Minas — provável raiz interior de Goiás (coerente com atender Planaltina-GO)",
            "Sem perfil Doctoralia · sem site próprio (apesar de linktree ativo) · capital social do paciente não capturado em plataforma",
            "Sem Lattes ativo · sem PubMed além do case report SBCBM = perfil clínico, não acadêmico",
            "Hospital Santa Lúcia Asa Sul é provável base privada — base da clínica Diabesidade do Renato Teixeira",
            "Patrick deve abrir validando Bari Clube + #BARIGAN + selo azul = autoridade já existente · provocar 'cobre pelo programa, não pela cirurgia'",
            "Score 84 ÁGUIA · pitch mínimo R$ 38-42k · considerar entrada como case nacional ou versão premium",
        ],
    },

    "pitagoras-kieling": {
        "quote_manifesto": "+10.000 colonoscopias é número de cirurgião que parou de contar. Você cobra R$ 480 a consulta.",
        "narrativa_publica": "Você se formou em Medicina pela UFSM em 1994, fez residência em Cirurgia Geral no Hospital Ernesto Dorneles (1995-1997, bolsista MEC) e Coloproctologia no mesmo Ernesto Dorneles (1998-1999). Em 2014-2015 fez treinamento avançado IRCAD em Strasbourg. Em 2017 padronizou técnica videolaparoscópica colorretal no Instituto Lübeck São Paulo. Realizou <em>mais de 10.000 colonoscopias</em>. Hoje atua em 5 frentes hospitalares no Vale dos Sinos. Tem <em>928 avaliações 5 estrelas</em> no Doctoralia. <em>Currículo Champions League cobrando preço de Série C.</em>",
        "descobertas_publicas": [
            "<strong>UFSM Medicina (1989-1994)</strong> · Residência Cirurgia Geral Ernesto Dorneles (1995-1997, bolsista MEC) · Residência Coloproctologia Ernesto Dorneles (1998-1999)",
            "<strong>IRCAD Strasbourg/Latam (2014-2015)</strong> — treinamento avançado em videolaparoscopia",
            "<strong>Padronização videolaparoscópica colorretal · Instituto Lübeck São Paulo (2017)</strong> — referência absoluta em cirurgia colorretal minimamente invasiva no Brasil",
            "<strong>+10.000 colonoscopias realizadas</strong> · volume top-tier",
            "<strong>928 avaliações verificadas 5 estrelas no Doctoralia</strong> — palavras dos pacientes: 'paciência, calma, didático, não tem pressa, gentileza'",
            "<strong>5 frentes hospitalares simultâneas</strong>: Centenário, Regina NH, Unimed Vale dos Sinos, Sapucaia do Sul (Diretor Técnico Endoscopia Digestiva), Endosinos (Diretor Técnico desde 2005)",
            "<strong>Co-autor 1991</strong> — 'Sugestão Preliminar do Efeito Trivers-Willard em Seres Humanos' (Brazilian Journal of Genetics) · ainda na graduação",
            "<strong>Co-autor 2009</strong> — 'Adenoma Mucinoso de Apêndice' (58º Congresso Brasileiro de Coloproctologia)",
            "<strong>Trilíngue</strong>: Português · Espanhol · Inglês",
            "<strong>+16.000 procedimentos acumulados</strong> na Endosinos (CNPJ 07.370.887/0001-59 desde 2005)",
        ],
        "pitch_direcionado": [
            ("Capturar valor do que entrega",
             "R$ 480 consulta sendo IRCAD + Lübeck = 50% abaixo do que coloproctologistas com metade do CV cobram em SP/POA. Subir pra R$ 800-1.200 imediatamente · paciente paga pelo Ferrari, não pela Toyota"),
            ("Estruturar produto premium · screening + cirurgia",
             "Programa 'Saúde Colorretal Premium' — screening completo + colonoscopia + acompanhamento + cirurgia eletiva quando indicada · ticket pacote R$ 12-22k. 928 reviews 5⭐ é base pra empacotar prova social premium"),
            ("Captação inversa · sair do Vale dos Sinos",
             "Atrair pacientes de POA, Caxias, Pelotas, Santa Maria. IRCAD + Lübeck atrai paciente que não confia em cirurgião regional"),
            ("Construir marca além de você",
             "Recrutar 1-2 coloproctologistas júnior pra escalar volume mantendo o nome como marca-mãe. Lançar mentoria/curso para coloproctologistas que querem migrar pra videolaparoscopia avançada (replicar IRCAD/Lübeck). Retomar produção científica"),
        ],
        "pontos_internos": [
            "55 anos · UFSM 1994 · 25 anos de carreira",
            "Sócio único da Endosinos · capital R$88k = clínica enxuta, não estrutura empresarial",
            "Sem confirmação de pai médico ('Júnior' fato civil mas pai sem rastro digital · provavelmente leigo geração 1940-50 possivelmente falecido)",
            "Sobrenome alemão (Pomerânia/Holstein) · São Leopoldo é cidade-marco da imigração alemã (1824) · base luterana possível",
            "Geração analógica · email Hotmail · sites Wix simples · Google Business · presença básica · enorme upside de marketing",
            "Cabeça científica precoce (paper genética 1991) que não virou linha de pesquisa — pode haver frustração de não ter virado professor",
            "Patrick deve usar gancho emocional 'Júnior virou referência. E o Pitágoras Sênior, pai, viu até onde?' (gatilho família)",
            "928 reviews 5⭐ é ouro de copy: 'paciência', 'não tem pressa', 'didático' = identidade técnica-discreta pra preservar",
            "Aceita Unimed + IPÊ (servidor RS) + particular · IPÊ tem volume baixo de ticket",
        ],
    },

    "paulo-victor-pereira": {
        "quote_manifesto": "Caso de sucesso clínico que ainda não virou negócio.",
        "narrativa_publica": "Você é sócio fundador da ICOD desde 2018 — oito anos consolidando uma das clínicas multidisciplinares ortopédicas mais respeitadas de Brasília, com presença em Águas Claras e Paranoá. É o único cirurgião de pé e tornozelo dos dez sócios. Tem 151 avaliações verificadas no Doctoralia, todas cinco estrelas. Os pacientes usam as mesmas três palavras pra te descrever: <em>atencioso, claro, tranquilo.</em> <strong>Hoje é a segunda call CPP em 2 dias — diagnóstico aprofundado.</strong>",
        "descobertas_publicas": [
            "<strong>CRM-DF 22186 · RQE 17862</strong> — Ortopedia e Traumatologia, subespecialização Pé e Tornozelo",
            "<strong>Sócio fundador ICOD desde 01/06/2018</strong> — Instituto da Coluna Vertebral, Ortopedia, Dor e Otorrino (CNPJ 30.599.744/0001-35)",
            "<strong>Único cirurgião de pé e tornozelo dos 10 sócios</strong> da ICOD — sem concorrência interna no nicho",
            "<strong>2 endereços</strong>: Águas Claras (Albany Medical Center) + Paranoá",
            "<strong>151 avaliações verificadas Doctoralia · 5,0 estrelas</strong>",
            "<strong>Carteira robusta de convênios institucionais</strong>: Postal Saúde · Saúde Caixa · BACEN · STF-MED · TST/TRE Saúde · Casembrapa · Conab · Serpro",
        ],
        "pitch_direcionado": [
            ("Eleger sub-nicho dentro de pé e tornozelo",
             "Esportivo? Hálux valgo? Pé do diabético? Performance? Escolher UMA aresta torna você inesquecível em vez de mais um do guarda-chuva ICOD"),
            ("Construir marca pessoal paralela à ICOD",
             "Dr. Giancarlo Mariano e Dr. Joubert Toledo já têm clínica própria além do instituto — modelo paralelo, não conflitante. Hora de ter site, Instagram pessoal e jornada própria"),
            ("Subir ticket de R$350 para R$800-1.200",
             "Consulta avaliativa premium diferenciada da ICOD"),
            ("Reduzir convênios de 54+ para 5-10 estratégicos",
             "Manter os de ticket mais alto, sair de Postal/Camed/Saúde Caixa"),
        ],
        "pontos_internos": [
            "**SEGUNDA CALL CPP em 2 dias** — diagnóstico aprofundado · ele já ouviu nosso pitch ontem",
            "Sem Lattes, sem PubMed, sem palestras — operador 100% prático, não acadêmico",
            "Hierarquia interna ICOD: Giancarlo Mariano é RT (estrela técnica), Joubert Toledo é admin (clínica paralela em Lago Sul). Paulo Victor é o sócio operador",
            "Demografia pacientes: 40-70 anos · funcionários públicos federais e aposentados · classe média (não classe alta)",
            "1 review crítica (Esmeraldino, ago/24): 'faz cirurgia mas a mão de obra tem que pagar' = teto de monetização",
            "Hipótese residência: HBDF ou HRAN (rotas clássicas DF) + fellowship HOG Goiânia ou IOT-HCFMUSP. CONFIRMAR",
            "Perfil presumido: introvertido técnico, alta empatia, baixa autopromoção. NÃO é alfa-influencer",
        ],
    },

    "ildo-golff": {
        "quote_manifesto": "Você é o único cirurgião do Brasil que sabe ler um DRE sem precisar do contador traduzir.",
        "narrativa_publica": "Você é bacharel em <em>Ciências Contábeis pela Univel</em> (2010) — ANTES de fazer Medicina pela FAG (2013-2018). Fez 5 anos de residência em Neurocirurgia no Hospital Universitário Cajuru / PUC-PR (2019-2024). Voltou pra Cascavel em 2024-2025 como preceptor adjunto da Neurocirurgia no Hospital São Lucas. Seu pai, Ildo Valter Golff, é economista e perito judicial do TRT9 — atua em Cascavel há décadas, com 146 processos como perito registrado no Jusbrasil. <em>Você compartilha o mesmo prédio comercial com ele.</em>",
        "descobertas_publicas": [
            "<strong>CRM-PR 40772</strong> · 38 anos · email golff87@hotmail.com (nascido 1987)",
            "<strong>Bacharel em Ciências Contábeis · Univel · 2010</strong> — combinação raríssima entre cirurgiões",
            "<strong>Medicina FAG (2013-2018)</strong> — turma TXVII / 'Cássio Franco'",
            "<strong>Estágio Clínica Médica · HUOP (Unioeste) · 2015/16</strong>",
            "<strong>Residência Neurocirurgia · Hospital Universitário Cajuru · PUC-PR · Curitiba · 5 anos (2019-2024)</strong> — referência neurocirurgia PR",
            "<strong>Preceptor adjunto Neurocirurgia · Hospital São Lucas Cascavel</strong> · R. Eng. Rebouças 2219",
            "<strong>Pai: Ildo Valter Golff</strong> — economista/consultor + perito judicial TRT9 · 146 processos como perito · escritório Av. Paraná 3035 sala 74 + Rua Santa Catarina 1947",
            "<strong>Clínica Médica Dr. Golff Ltda</strong> · CNPJ 32.253.406/0001-72 · fundada 13/12/2018 · Rua Santa Catarina 1947 · capital R$ 5 mil",
            "<strong>Sócios: Ildo Valter Golff Filho + Willyan Hardt Golff (irmão)</strong>",
            "<strong>Co-autor 2024</strong> · 'Correlation between Profile of Intracranial Hemorrhages and GOS at Discharge' (J. Neurology Research Reviews)",
            "<strong>Trabalho graduação 2017</strong> · 'Aderência à Insulinoterapia em Diabetes Mellitus tipo 1 em Cascavel' (THEMA ET SCIENTIA v.7)",
            "<strong>Pronto Atendimento Santa Helena/PR</strong> · 20h/sem como clínico (renda complementar SUS pós-residência)",
        ],
        "pitch_direcionado": [
            ("Capitalizar a vantagem competitiva única (contábil + médico)",
             "Você é provavelmente o único cirurgião do Brasil que sabe ler um DRE sem precisar do contador traduzir. Isso não é hobby — é vantagem competitiva única pro consultório premium"),
            ("Sair da invisibilidade digital (território VIRGEM)",
             "Cascavel inteira não te conhece ainda. Vácuo de mídia (zero Catve/CGN) + zero Instagram = território livre. Abrir IG, Doctoralia, site próprio em 30 dias"),
            ("Eleger sub-nicho dentro de neurocirurgia",
             "Coluna minimamente invasiva? Tumor cerebral? Funcional? Pediátrica? Escolher UMA aresta + fazer parceria de retaguarda contábil com o pai (família como ativo)"),
            ("Plano de saída do PA Santa Helena",
             "Você fez 5 anos em Curitiba pra voltar — não pra ser plantonista 20h/sem em Santa Helena. Estruturar consultório premium em Cascavel + reduzir SUS gradualmente"),
        ],
        "pontos_internos": [
            "Sobrenome Golff + Hardt (mãe ou avó) = ascendência alemã, padrão típico do oeste do PR · Cascavel tem comunidade luterana herdada",
            "Cascavel = Unimed-mente refém · 17 hospitais · 613 médicos cooperados · 22 cidades. Quem não credencia, não fatura volume — mas margem alta só em particular",
            "Capital social da clínica R$ 5 mil = casca corporativa, ainda não operada como empresa de verdade · sinal de subdimensionamento",
            "Família já compartilha estrutura física: pai cuida da contabilidade/perícia, filho atende. Modelo de retaguarda PERFEITO já existente",
            "Recém-formado da PUC-Cajuru (especialidade renomada) + capacitação contábil + pai economista/perito = perfil 'filho médico com ZERO dor de retaguarda contábil mas ALTA dor de monetização clínica'",
            "Patrick deve usar contabilidade como gancho ouro #1 + 'pai perito' como gancho emocional",
            "Hipótese religiosa: católico ou presbiteriano/luterano (sobrenome alemão + tradição Cascavel) · Lagoinha/Verdade/IPCC têm peso evangélico forte",
            "Score 72 GAVIÃO confirmado base CPP",
            "Provável próxima fase: estruturar 'Clínica Dr. Golff' como negócio familiar com irmão Willyan + pai retaguarda",
        ],
    },

    "vitor-vilhegas": {
        "quote_manifesto": "Em Adamantina você é praticamente monopólio do joelho. Isso é poder de precificação que NENHUM ortopedista de capital tem.",
        "narrativa_publica": "Você se formou em Medicina pela UNOESTE Pres. Prudente, fez residência em Ortopedia na Santa Casa de Ourinhos-SP, e fez fellowship em Cirurgia do Joelho na Ortocity São Paulo (grupo SBCJ certificado, 16 cirurgiões, ~700 cirurgias/ano). Em julho de 2025 foi destaque no <em>Siga Mais</em> de Adamantina como <strong>pioneiro regional em prótese unicompartimental de joelho com navegação intra-operatória</strong> — trouxe Dr. Álvaro Souto de Dourados/MS como cirurgião convidado. Família Vilhegas (linhagem nobre espanhola Toledo) tem peso em Pres. Prudente — pai/tio Sérgio Vilhegas é dentista UNOESTE. <em>Você foi pra Adamantina construir nome próprio.</em>",
        "descobertas_publicas": [
            "<strong>CRM-SP 170724 · RQE 98735</strong>",
            "<strong>Graduação UNOESTE</strong> Pres. Prudente · Residência Ortopedia Santa Casa de Ourinhos-SP · Fellowship Cirurgia do Joelho Ortocity São Paulo",
            "<strong>Pioneiro regional em prótese unicompartimental de joelho com navegação intra-operatória</strong> · Siga Mais 21/07/2025 · Adamantina-SP",
            "Cirurgião convidado: <strong>Dr. Álvaro Souto (Dourados-MS)</strong> · anestesista parceiro Dr. Eduardo Motoyama",
            "<strong>Consultório próprio · Av. Rio Branco 61 · Centro Adamantina-SP</strong> (CEP 17800-000) · mudança recente",
            "<strong>Santa Casa de Adamantina</strong> (CNES 2077647) · 35+ especialidades · principal hospital da cidade",
            "<strong>Família Vilhegas</strong> · sobrenome de origem espanhola Toledo · linhagem D. Diogo Ortiz · brasão com dois braços armados e caldeira",
            "<strong>Pai/tio Sérgio Vilhegas</strong> · odontólogo · professor UNOESTE · especializado em Ortodontia/Ortopedia Facial · clínica Vila Roberto Pres. Prudente",
            "<strong>Provável irmão Dr. João Paulo Vilhegas</strong> · dentista Pres. Prudente",
            "<strong>Praticamente monopólio do joelho em Adamantina</strong> · Top 10 ortopedistas regional · catálogo BoaConsulta",
        ],
        "pitch_direcionado": [
            ("Capitalizar o pioneirismo da navegação como campanha de 1 ano",
             "A cirurgia da prótese unicompartimental com navegação foi a primeira da região. Rendeu UMA matéria local em 2025 e morreu. Material gigante de marketing nunca foi convertido em filme/funil/conteúdo. 12 ângulos diferentes (técnica + paciente + equipe + resultado + região)"),
            ("Drenar paciente de raio 100km",
             "Adamantina (35k) + Lucélia + Osvaldo Cruz + Dracena + Mariápolis + Pacaembu + Pres. Prudente. Mapeamento de captação · parcerias estratégicas · mídia regional dirigida"),
            ("Empacotar 'Programa Joelho Premium' com ticket coerente",
             "Avaliação + Cirurgia + Recuperação · ticket único R$ 25-45k. Auditar mix particular vs convênio · plano de saída gradual"),
            ("Posicionar 'Vilhegas do joelho' como categoria pessoal",
             "Não 'o filho do Sérgio' nem 'um cirurgião de Adamantina'. O Vilhegas do joelho da Nova Alta Paulista. Capital simbólico da família + capital técnico próprio"),
        ],
        "pontos_internos": [
            "Família Vilhegas é capital simbólico (linhagem nobre espanhola Toledo · D. Diogo Ortiz Bispo de Viseu) — ele é orgulhoso disso, é ativo de identidade",
            "Saiu de Pres. Prudente (família estabelecida) → Adamantina (mercado virgem · vira referência regional) = decisão consciente de construir nome próprio fora da sombra paterna",
            "Hipótese identidade: 'médico da família de dentistas que escolheu Adamantina pra sair da sombra do Sérgio' = identidade central a ser explorada",
            "Investiu em equipamento (navegação) + casa nova + presença digital + cirurgião convidado MS = ele JÁ entendeu marketing, falta sistema",
            "Adamantina (35k hab) é praticamente monopólio do joelho · poder de precificação que ortopedista de capital não tem · só funciona se paciente sai convencido que ele É O CARA",
            "Faz por intuição (não método) · diferença = 3x no ticket médio",
            "Score perfil GAVIÃO · não está na base CPP · pagou R$1.097 mesmo morando em cidade pequena = sinal forte de fome",
            "Patrick deve abrir validando Ortocity + pioneirismo navegação · provocar sobre Adamantina ser monopólio sub-aproveitado",
        ],
    },

    "alander-sobreira": {
        "quote_manifesto": "Você é Rush cobrando preço de Ceará. O problema não é técnica — é permissão.",
        "narrativa_publica": "Você se formou em Medicina pela Faculdade de Medicina de Juazeiro do Norte (FMJ) em 2006, fez residência em Neurocirurgia no Hospital Municipal Odilon Behrens de Belo Horizonte, e <em>fellowship em Coluna Minimamente Invasiva no Rush University Medical Center, Chicago</em>. Voltou pra Fortaleza em 2013 e construiu o serviço de Neurocirurgia da Rede OTO Kora desde 2014, onde é Coordenador. Tem 28.000 seguidores no Instagram, 435 posts, e em 24 de dezembro de 2025 escreveu: <em>'2025 me ensinou que tudo começa e termina em Deus. Quando a técnica alcança seu limite, é a graça que sustenta.'</em> Atende em Fortaleza + Sobral. Foi palestrante do 9º Congresso Cearense de Neurologia e Neurocirurgia em 2025. <em>Você é referência regional. A próxima fronteira é nacional.</em>",
        "descobertas_publicas": [
            "<strong>CRM-CE 10374 · RQE 6258</strong> · Neurocirurgião · Coluna MIS + Crânio",
            "<strong>FMJ Faculdade de Medicina de Juazeiro do Norte · 2006</strong> · TCC sobre Status Epilepticus · Cariri/CE (escola da terra)",
            "<strong>Residência Neurocirurgia · Hospital Municipal Odilon Behrens · Belo Horizonte</strong> · escola tradicional MG",
            "<strong>Fellowship · Rush University Medical Center · Chicago/USA · Coluna Minimamente Invasiva (MIS)</strong> · provavelmente 2011-2013",
            "<strong>Coordenador Neurocirurgia · Rede OTO Kora · Hospital Oto Aldeota · Fortaleza · desde 2014</strong> (12 anos de liderança institucional)",
            "<strong>13 anos atuando em Fortaleza desde 2013</strong> · trilíngue (Português · Inglês · provável Espanhol)",
            "<strong>Atende Fortaleza + Sobral</strong> · rota interior + capital",
            "<strong>Palestrante 9º Congresso Cearense de Neurologia e Neurocirurgia (NeuroCeará 2025)</strong>",
            "<strong>Comentarista de saúde pública na BAND-CE</strong> · artigos sobre Doença de Parkinson",
            "<strong>@dralandersobreira · 28.000 seguidores · 435 posts</strong> · engajamento real (64 seg/post)",
            "<strong>Cristão público</strong> · frase-âncora 24/12/2025: 'tudo começa e termina em Deus, a graça é que sustenta quando a técnica alcança seu limite' · Facebook bio: 'servo de Deus'",
            "<strong>Endereço Rua Monsenhor Bruno 2332 · Fortaleza</strong>",
        ],
        "pitch_direcionado": [
            ("Capturar valor real do que entrega",
             "Você opera o que 95% dos neuros do Nordeste mandam pra São Paulo. Por que cobra preço de Ceará? Subir ticket consulta avaliativa pra R$ 1.500-2.500 (coerente com Rush MIS). Doctoralia VAZIA = capturar 50 reviews em 30 dias"),
            ("Empacotar autoridade em produto premium",
             "Programa 'Coluna Premium · Avaliação MIS + Cirurgia + Recuperação' · ticket pacote R$ 35-65k. E-book + curso online sobre Coluna MIS (escala fora da agenda cirúrgica). Newsletter mensal pra neuros + ortopedistas + médicos de família NE"),
            ("Captação inversa nacional",
             "Paciente de Recife, Natal, Salvador, Belém, Manaus pra Fortaleza. 28k seguidores não estão todos em Fortaleza — é audiência nordestina não monetizada"),
            ("Virar referência nacional cristã na neurocirurgia",
             "Lançar livro de Coluna Minimamente Invasiva (autoridade Rush convertida em produção científica). Imersão presencial · cirurgia ao vivo. Mentoria pra neurocirurgiões cristãos (replicar trajetória interior→cima · médico-servo)"),
        ],
        "pontos_internos": [
            "**EIXO DE ALIANÇA #1 · FÉ COMPARTILHADA** — Patrick também é cristão · ele deve usar isso como abertura sem performance · 'eu li seu post de 24 de dezembro · esse é o eixo da mentoria, não só técnica de venda'",
            "**EIXO DE ALIANÇA #2 · TRAJETÓRIA INTERIOR→CIMA** — Cariri (Juazeiro) → BH (Behrens) → Chicago (Rush) → Fortaleza+Sobral · ele fez o salto que poucos fazem",
            "Doctoralia VAZIA · zero PubMed · zero livro · zero curso · zero produto = 3 alavancas mortas, 2 eixos de aliança",
            "28k IG com 435 posts = engajamento real (64 seg/post) · não é audiência inflada",
            "Frequência IG baixa-média (2-4 posts/mês em 2025) · plataforma sub-aproveitada · Threads tem só 3.208 seguidores",
            "Mix de conteúdo: 50% técnica + 25% fé + 25% saúde pública · NÃO é influencer-de-Maybach · médico-pastor",
            "Igreja específica não declarada · provável estilo evangélico (Lagoinha, Videira, IBA Aldeota) ou católico — perguntar discreto · NÃO confirmar família/esposa sem ele abrir",
            "Pagou R$1k mesmo sendo Águia consolidada = sente que estagnou no patamar regional · sabe que tem mais teto",
            "Provável próxima fronteira: referência nacional em Coluna MIS via livro/curso/podcast",
            "Score 84 ÁGUIA · Top 11 da lista AAA · pitch mínimo R$ 38-42k · considerar entrada como case ou versão premium",
            "Frase de fechamento: 'CPP só vai te ajudar a cobrar como Rush e atender como Cristo'",
        ],
    },
}
